# Generated by Django 3.1.1 on 2020-10-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagecertificate',
            name='certificate_type',
            field=models.CharField(choices=[('IELTS General', 'IELTS General'), ('IELTS Academic', 'IELTS Academic'), ('TOEFL', 'TOEFL'), ('GMAT', 'GMAT'), ('GRE General', 'GRE General'), ('GRE Chemistry', 'GRE Chemistry'), ('GRE Mathematics', 'GRE Mathematics'), ('GRE Literature', 'GRE Literature'), ('GRE Biology', 'GRE Biology'), ('GRE Physics', 'GRE Physics'), ('GRE Psychology', 'GRE Psychology'), ('Duolingo', 'Duolingo')], default='TOEFL', help_text='Based on endpoint just some types are allowed to insert not all certificate types.', max_length=64),
        ),
    ]
