# Generated by Django 3.1.1 on 2020-10-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similarApply', '0002_auto_20201013_1734'),
        ('form', '0002_auto_20201013_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wanttoapply',
            name='grades',
        ),
        migrations.AddField(
            model_name='wanttoapply',
            name='grade',
            field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PH.D', 'Phd'), ('Post Doc', 'Post Doc')], default='Bachelor', max_length=128),
        ),
        migrations.DeleteModel(
            name='GradeModel',
        ),
    ]
