# Generated by Django 3.1.1 on 2021-06-19 12:30

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedRedeemCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('available_rounds', models.IntegerField(default=1)),
                ('referral_id', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('score', models.IntegerField(default=0)),
                ('duration', models.SmallIntegerField(default=0, help_text='In seconds')),
                ('answered_questions', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='RedeemCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('usage_limit', models.IntegerField(default=2000)),
                ('usages', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsedFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('feature', models.CharField(choices=[('Analyze', 'Analyze')], max_length=32)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wherebetter.participant')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='redeem_codes',
            field=models.ManyToManyField(through='wherebetter.AppliedRedeemCode', to='wherebetter.RedeemCode'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appliedredeemcode',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wherebetter.participant'),
        ),
        migrations.AddField(
            model_name='appliedredeemcode',
            name='redeem_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wherebetter.redeemcode'),
        ),
        migrations.CreateModel(
            name='InviteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, choices=[('Telegram', 'Telegram'), ('Facebook', 'Facebook'), ('Linkedin', 'Linkedin'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram')], max_length=16, null=True)),
                ('invite_date', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wherebetter_inviteinfo_as_invited', to=settings.AUTH_USER_MODEL)),
                ('invitor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wherebetter_inviteinfo_as_invitor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('invitor_user', 'invited_user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='appliedredeemcode',
            unique_together={('participant', 'redeem_code')},
        ),
    ]
