# Generated by Django 3.1.1 on 2020-12-30 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('storeBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='real_type',
            field=models.ForeignKey(default=None, null = True, editable=False, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
    ]
