# Generated by Django 3.1.1 on 2021-02-15 11:46

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    ContentType = apps.get_model("contenttypes", "contenttype")
    SoldApplyProfileGroup = apps.get_model("applyprofilestore", "soldapplyprofilegroup")
    SoldTimeSlotSale = apps.get_model("storeBase", "soldtimeslotsale")
    SoldProduct = apps.get_model('storeBase', 'soldproduct')

    sold_apply_profile_group_ct = ContentType.objects.get(app_label="applyprofilestore", model="soldapplyprofilegroup")
    sold_time_slot_sale_ct = ContentType.objects.get(app_label="storeBase", model="soldtimeslotsale")
    sold_product_ct = ContentType.objects.get(app_label='storeBase', model='soldproduct')
    print('start')
    for obj in SoldApplyProfileGroup.objects.all():
        obj.real_type = sold_apply_profile_group_ct
        obj.save()
    for obj in SoldTimeSlotSale.objects.all():
        obj.real_type = sold_time_slot_sale_ct
        obj.save()
    for obj in SoldProduct.objects.filter(real_type__isnull=True):
        obj.real_type = sold_product_ct
        obj.save()
        print(obj)

    print('real type is now set')


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('storeBase', '0001_initial'),
        ('storePackages', '0001_initial'),
        ('applyprofilestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='real_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.RunPython(
            code=forwards_func, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='real_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT,
                                    to='contenttypes.contenttype'),
        ),
    ]
