# Generated by Django 3.1.1 on 2021-02-15 11:46

from django.db import migrations, models
import django.db.models.deletion
from django.db import connection


def forwards_func(apps, schema_editor):
    db_name: str = connection.settings_dict['NAME']

    if db_name.startswith('test'):
        return

    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    ContentType = apps.get_model("contenttypes", "contenttype")
    print("OOO1")

    SoldApplyProfileGroup = apps.get_model("applyprofilestore", "soldapplyprofilegroup")
    print("OOO2")

    sold_apply_profile_group_ct = ContentType.objects.get(app_label="applyprofilestore", model="soldapplyprofilegroup")
    sold_product_ct = ContentType.objects.get(app_label='storeBase', model='soldproduct')

    for obj in SoldApplyProfileGroup.objects.all():
        obj.real_type = sold_apply_profile_group_ct
        obj.save()

    print('real type is now set')


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('storeBase', '0001_initial'),
        ('applyprofilestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='real_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.RunPython(
            code=forwards_func, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='real_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT,
                                    to='contenttypes.contenttype'),
        ),
    ]
