# Generated by Django 3.1.1 on 2021-02-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20210201_1003'),
        ('orders', '0002_auto_20210201_1003'),
        ('storeBase', '0002_auto_20210215_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldtimeslotsale',
            name='soldproduct_ptr',
        ),
        migrations.RemoveField(
            model_name='timeslotsale',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='SoldTimeSlotSalePaymentInfo',
        ),
        migrations.DeleteModel(
            name='SoldTimeSlotSale',
        ),
        migrations.DeleteModel(
            name='TimeSlotSale',
        ),
    ]
