# Generated by Django 3.1.1 on 2020-10-04 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
        ('basicProducts', '0001_initial'),
        ('consultants', '0001_initial'),
        ('storeBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldtimeslotrate',
            name='sold_time_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storeBase.soldtimeslotsale'),
        ),
        migrations.AddField(
            model_name='soldbasicproductratefieldthrough',
            name='basic_product_rate_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.basicproductratefield'),
        ),
        migrations.AddField(
            model_name='soldbasicproductratefieldthrough',
            name='sold_basic_product_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.soldbasicproductrate'),
        ),
        migrations.AddField(
            model_name='soldbasicproductrate',
            name='rates',
            field=models.ManyToManyField(through='comments.SoldBasicProductRateFieldThrough', to='comments.BasicProductRateField'),
        ),
        migrations.AddField(
            model_name='soldbasicproductrate',
            name='sold_basic_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basicProducts.soldbasicproduct'),
        ),
        migrations.AddField(
            model_name='consultantcomment',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultants.consultantprofile'),
        ),
        migrations.AddField(
            model_name='consultantcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultantadmincomment',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_reply', to='comments.consultantcomment'),
        ),
        migrations.AddField(
            model_name='basicproductratefield',
            name='basic_product_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comments.basicproductrate'),
        ),
        migrations.AddField(
            model_name='basicproductrate',
            name='basic_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basicProducts.basicproduct'),
        ),
    ]
