# Generated by Django 3.1.1 on 2021-02-01 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storeBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('consultant_id', models.IntegerField(blank=True, null=True)),
                ('user_login_url', models.URLField(blank=True, max_length=1024)),
                ('consultant_login_url', models.URLField(blank=True, max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sold_time_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storeBase.soldtimeslotsale')),
            ],
        ),
    ]
