# Generated by Django 3.1.1 on 2020-10-03 08:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import sNeeds.apps.users.consultants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', ckeditor.fields.RichTextField()),
                ('profile_picture', models.ImageField(upload_to=sNeeds.apps.users.consultants.models.get_consultant_image_path)),
                ('aparat_link', models.URLField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to=sNeeds.apps.users.consultants.models.get_consultant_resume_path)),
                ('slug', models.SlugField(help_text='lowercase pls', unique=True)),
                ('active', models.BooleanField(default=True)),
                ('time_slot_price', models.PositiveIntegerField()),
                ('rate', models.FloatField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('postdoc', 'Post Doc'), ('unknown', 'Unknown')], max_length=256)),
                ('order', models.PositiveIntegerField(help_text='Enter number above 0')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultants.consultantprofile')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.fieldofstudy')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.university')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='universities',
            field=models.ManyToManyField(blank=True, through='consultants.StudyInfo', to='account.University'),
        ),
    ]
