# Generated by Django 3.1.1 on 2020-10-01 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='studyinfo',
            unique_together={('consultant', 'university', 'field_of_study', 'grade', 'order')},
        ),
    ]
