# Generated by Django 3.1.1 on 2020-10-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201004_1434'),
        ('consultants', '0002_auto_20201004_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyinfo',
            old_name='field_of_study',
            new_name='major',
        ),
        migrations.AlterUniqueTogether(
            name='studyinfo',
            unique_together={('consultant', 'university', 'major', 'grade', 'order')},
        ),
    ]
