# Generated by Django 2.2.3 on 2020-07-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200627_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='language_listening',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='language_reading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='language_speaking',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='language_writing',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
