# Generated by Django 2.2.3 on 2020-07-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20200714_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='language_certificate_overall',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
