# Generated by Django 2.2.3 on 2020-05-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20200714_2219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentDetailedInfo',
        ),
    ]
