# Generated by Django 2.2.3 on 2020-07-16 09:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sNeeds.apps.account.models
import sNeeds.apps.account.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0017_delete_StudentDetailed_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='FormMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='FormMajorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='FormUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FormUniversityThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduate_in', models.SmallIntegerField(help_text='In Gregorian', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('thesis_title', models.CharField(blank=True, max_length=512, null=True)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.FormGrade')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.FormMajor')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageCertificateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageCertificateTypeThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaking', models.DecimalField(decimal_places=2, max_digits=5)),
                ('listening', models.DecimalField(decimal_places=2, max_digits=5)),
                ('writing', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reading', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overall', models.DecimalField(decimal_places=2, max_digits=5)),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.LanguageCertificateType')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('publish_year', models.SmallIntegerField(help_text='In Gregorian', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
            ],
        ),
        migrations.CreateModel(
            name='UniversityWantToApplyThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=256)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.FormGrade')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.University')),
            ],
        ),
        migrations.AlterField(
            model_name='studentformapplysemesteryear',
            name='year',
            field=models.SmallIntegerField(help_text='In Gregorian', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='studentformfieldschoice',
            name='category',
            field=models.CharField(choices=[('marital_status', 'marital_status'), ('publication_type', 'publication_type'), ('major_type', 'major_type'), ('payment_affordability', 'payment_affordability'), ('publication_which_author', 'publication_which_author')], max_length=256),
        ),
        migrations.CreateModel(
            name='WantToApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Country')),
                ('semester_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.StudentFormApplySemesterYear')),
                ('universities', models.ManyToManyField(through='account.UniversityWantToApplyThrough', to='account.University')),
            ],
        ),
        migrations.AddField(
            model_name='universitywanttoapplythrough',
            name='want_to_apply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.WantToApply'),
        ),
        migrations.CreateModel(
            name='StudentDetailedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)])),
                ('prefers_full_fund', models.BooleanField(default=False)),
                ('prefers_half_fund', models.BooleanField(default=False)),
                ('prefers_self_fund', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, max_length=1024, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to=sNeeds.apps.account.models.get_student_resume_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), sNeeds.apps.account.validators.validate_resume_file_size])),
                ('related_work_experience', models.PositiveIntegerField(blank=True, help_text='In months', null=True)),
                ('academic_break', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('olympiad', models.CharField(blank=True, max_length=256, null=True)),
                ('powerful_recommendation', models.BooleanField(default=False)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('language_certificates', models.ManyToManyField(through='account.LanguageCertificateTypeThrough', to='account.LanguageCertificateType')),
                ('marital_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marital_status', to='account.StudentFormFieldsChoice')),
                ('payment_affordability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_affordability', to='account.StudentFormFieldsChoice')),
                ('publications', models.ManyToManyField(to='account.Publication')),
                ('universities', models.ManyToManyField(through='account.FormUniversityThrough', to='account.FormUniversity')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('want_to_apply', models.ManyToManyField(to='account.WantToApply')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('student_form_fields_choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_type', to='account.StudentFormFieldsChoice')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.PublicationType'),
        ),
        migrations.AddField(
            model_name='publication',
            name='which_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_which_author', to='account.StudentFormFieldsChoice'),
        ),
        migrations.AddField(
            model_name='languagecertificatetypethrough',
            name='student_detailed_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentDetailedInfo'),
        ),
        migrations.AddField(
            model_name='formuniversitythrough',
            name='major_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='major_type', to='account.StudentFormFieldsChoice'),
        ),
        migrations.AddField(
            model_name='formuniversitythrough',
            name='student_detailed_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentDetailedInfo'),
        ),
        migrations.AddField(
            model_name='formuniversitythrough',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.FormUniversity'),
        ),
    ]
