# Generated by Django 2.2.3 on 2020-07-16 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20200716_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitywanttoapplythrough',
            name='major_type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='want_to_apply_major_type', to='account.StudentFormFieldsChoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formuniversitythrough',
            name='major_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='university_major_type', to='account.StudentFormFieldsChoice'),
        ),
        migrations.AlterField(
            model_name='studentformfieldschoice',
            name='category',
            field=models.CharField(choices=[('marital_status', 'marital_status'), ('publication_type', 'publication_type'), ('university_major_type', 'university_major_type'), ('want_to_apply_major_type', 'want_to_apply_major_type'), ('payment_affordability', 'payment_affordability'), ('publication_which_author', 'publication_which_author')], max_length=256),
        ),
    ]
