# Generated by Django 2.2.3 on 2020-07-16 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20200716_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitywanttoapplythrough',
            name='major_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.FormMajorType'),
        ),
    ]
