# Generated by Django 2.2.3 on 2020-07-16 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20200716_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationtype',
            name='student_form_fields_choice',
        ),
        migrations.AddField(
            model_name='publicationtype',
            name='type',
            field=models.CharField(default='type1', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='publish_year',
            field=models.SmallIntegerField(help_text='In Gregorian', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='studentformapplysemesteryear',
            name='year',
            field=models.SmallIntegerField(help_text='In Gregorian', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
