# Generated by Django 2.2.3 on 2020-07-16 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20200716_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationWhichAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='publication',
            name='which_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.PublicationWhichAuthor'),
        ),
    ]
