# Generated by Django 2.2.3 on 2020-07-16 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20200716_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAffordability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='payment_affordability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.PaymentAffordability'),
        ),
    ]
