# Generated by Django 2.2.3 on 2020-07-16 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20200716_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='formuniversitythrough',
            name='major_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='university_major_type', to='account.FormMajorType'),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='marital_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.MaritalStatus'),
        ),
        migrations.DeleteModel(
            name='StudentFormFieldsChoice',
        ),
    ]
