# Generated by Django 2.2.3 on 2020-07-16 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_basicformfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formgrade',
            name='id',
        ),
        migrations.RemoveField(
            model_name='formgrade',
            name='name',
        ),
        migrations.AddField(
            model_name='formgrade',
            name='basicformfield_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.BasicFormField'),
            preserve_default=False,
        ),
    ]
