# Generated by Django 2.2.3 on 2020-07-16 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20200716_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmajor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='formmajor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='formmajortype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='formmajortype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='formuniversity',
            name='id',
        ),
        migrations.RemoveField(
            model_name='formuniversity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='languagecertificatetype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='languagecertificatetype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='maritalstatus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='maritalstatus',
            name='title',
        ),
        migrations.RemoveField(
            model_name='paymentaffordability',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paymentaffordability',
            name='title',
        ),
        migrations.RemoveField(
            model_name='publicationtype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='publicationtype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='publicationwhichauthor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='publicationwhichauthor',
            name='title',
        ),
        migrations.AddField(
            model_name='formmajor',
            name='basicformfield_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.BasicFormField'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formmajortype',
            name='basicformfield_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.BasicFormField'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formuniversity',
            name='basicformfield_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.BasicFormField'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='languagecertificatetype',
            name='basicformfield_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.BasicFormField'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maritalstatus',
            name='basicformfield_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.BasicFormField'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentaffordability',
            name='basicformfield_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.BasicFormField'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicationtype',
            name='basicformfield_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.BasicFormField'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicationwhichauthor',
            name='basicformfield_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.BasicFormField'),
            preserve_default=False,
        ),
    ]
