# Generated by Django 2.2.3 on 2020-07-17 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20200716_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetailedinfo',
            name='publications',
        ),
        migrations.AddField(
            model_name='publication',
            name='form',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.StudentDetailedInfo'),
            preserve_default=False,
        ),
    ]
