# Generated by Django 2.2.3 on 2020-07-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20200716_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentformapplysemesteryear',
            name='semester',
            field=models.CharField(choices=[('spring', 'بهار'), ('summer', 'تابستان'), ('fall', 'پاییز\u200d'), ('winter', 'زمستان')], max_length=64),
        ),
    ]
