# Generated by Django 2.2.3 on 2020-07-16 14:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20200716_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='academic_break',
            field=models.PositiveIntegerField(blank=True, help_text='In years', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='universitywanttoapplythrough',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.FormMajor'),
        ),
    ]
