# Generated by Django 2.2.3 on 2020-07-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0029_auto_20200716_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitywanttoapplythrough',
            name='major_type',
        ),
        migrations.AddField(
            model_name='formmajor',
            name='major_type',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='account.FormMajorType'),
            preserve_default=False,
        ),
    ]
