# Generated by Django 2.2.3 on 2020-07-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20200716_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formuniversitythrough',
            name='major_type',
        ),
        migrations.AddField(
            model_name='formuniversity',
            name='is_college',
            field=models.BooleanField(default=False),
        ),
    ]
