# Generated by Django 2.2.3 on 2020-07-17 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20200717_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetailedinfo',
            name='want_to_apply',
        ),
        migrations.RemoveField(
            model_name='wanttoapply',
            name='universities',
        ),
        migrations.AddField(
            model_name='wanttoapply',
            name='form',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.StudentDetailedInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wanttoapply',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.FormGrade'),
        ),
        migrations.AddField(
            model_name='wanttoapply',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.FormMajor'),
        ),
        migrations.AddField(
            model_name='wanttoapply',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.University'),
        ),
    ]
