# Generated by Django 2.2.3 on 2020-07-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20200717_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniversityWantToApplyThrough',
        ),
    ]
