# Generated by Django 2.2.3 on 2020-07-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_delete_universitywanttoapplythrough'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='form',
            new_name='student_detailed_info',
        ),
        migrations.RenameField(
            model_name='wanttoapply',
            old_name='form',
            new_name='student_detailed_info',
        ),
        migrations.AddField(
            model_name='formuniversity',
            name='rank',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
