# Generated by Django 2.2.3 on 2020-07-18 20:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_auto_20200718_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMATCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytical_writing_assessment', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.0)])),
                ('integrated_reasoning', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('quantitative_and_verbal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(51)])),
                ('total', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(800)])),
            ],
        ),
        migrations.CreateModel(
            name='GRECertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitative', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('verbal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('analytical_writing', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
            ],
        ),
        migrations.AlterField(
            model_name='formuniversity',
            name='rank',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='formuniversitythrough',
            name='graduate_in',
            field=models.SmallIntegerField(help_text='In Gregorian', validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.MaritalStatus'),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='payment_affordability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.PaymentAffordability'),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='powerful_recommendation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='prefers_full_fund',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='prefers_half_fund',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='prefers_self_fund',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='wanttoapply',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.FormUniversity'),
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='gmat_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.GMATCertificate'),
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='gre_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.GRECertificate'),
        ),
    ]
