# Generated by Django 2.2.3 on 2020-07-19 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_auto_20200719_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='is_college',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='rank',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='formuniversitythrough',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.University'),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='universities',
            field=models.ManyToManyField(through='account.FormUniversityThrough', to='account.University'),
        ),
        migrations.AlterField(
            model_name='wanttoapply',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.University'),
        ),
        migrations.DeleteModel(
            name='FormUniversity',
        ),
    ]
