# Generated by Django 2.2.3 on 2020-07-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_auto_20200719_1700'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormUniversityThrough',
            new_name='UniversityThrough',
        ),
    ]
