# Generated by Django 2.2.3 on 2020-07-19 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_auto_20200719_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='slug',
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Country'),
        ),
    ]
