# Generated by Django 2.2.3 on 2020-07-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_auto_20200719_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Country'),
        ),
        migrations.AlterField(
            model_name='university',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
