# Generated by Django 2.2.3 on 2020-07-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_auto_20200719_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='picture',
            field=models.ImageField(null=True, upload_to='account/images/university-pictures'),
        ),
    ]
