# Generated by Django 2.2.3 on 2020-07-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_auto_20200719_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormMajorType',
            new_name='FieldOfStudyType',
        ),
        migrations.RemoveField(
            model_name='fieldofstudy',
            name='slug',
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='major_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.FieldOfStudyType'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='picture',
            field=models.ImageField(null=True, upload_to='account/images/field-of-study-pictures'),
        ),
        migrations.AlterField(
            model_name='universitythrough',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.FieldOfStudy'),
        ),
        migrations.AlterField(
            model_name='wanttoapply',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.FieldOfStudy'),
        ),
        migrations.DeleteModel(
            name='FormMajor',
        ),
    ]
