# Generated by Django 2.2.3 on 2020-07-20 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_auto_20200719_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetailedinfo',
            name='gmat_certificate',
        ),
        migrations.RemoveField(
            model_name='studentdetailedinfo',
            name='gre_certificate',
        ),
        migrations.AddField(
            model_name='gmatcertificate',
            name='student_detailed_info',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.StudentDetailedInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grecertificate',
            name='student_detailed_info',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.StudentDetailedInfo'),
            preserve_default=False,
        ),
    ]
