# Generated by Django 2.2.3 on 2020-07-23 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_auto_20200720_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
