# Generated by Django 2.2.3 on 2020-07-24 18:07

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_auto_20200723_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicformfield',
            name='name_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='basicformfield',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_search'], name='account_bas_name_se_1a51bc_gin'),
        ),
    ]
