# Generated by Django 2.2.3 on 2020-07-24 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_auto_20200723_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Country'),
        ),
        migrations.AlterField(
            model_name='university',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='account/images/university-pictures'),
        ),
    ]
