# Generated by Django 2.2.3 on 2020-07-26 15:38

# Because of below error for next migration "0051_auto_20200726_1902" this migration is added.
# psycopg2.errors.ObjectInUse: cannot ALTER TABLE "account_studentdetailedinfo" because it has pending trigger events
# Solution is adapted from below page.
# https://eshlox.net/2019/08/03/django-db-utils-operationalerror-cannot-alter-table-x-because-it-has-pending-trigger-events

from django.db import migrations


def postgres_migration_prep(apps, schema_editor):
    student_detailed_info = apps.get_model("account", "StudentDetailedInfo")
    fields = ("prefers_full_fund", "prefers_half_fund", "prefers_self_fund")
    for field in fields:
        filter_param = {"{}__isnull".format(field): True}
        update_param = {field: False}
        student_detailed_info.objects.filter(**filter_param).update(**update_param)
        
        
class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_add_trigram_similarity_index_to_basic_form_field'),
    ]

    operations = [
        migrations.RunPython(postgres_migration_prep, migrations.RunPython.noop)
    ]


