# Generated by Django 2.2.3 on 2020-07-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_add_trigram_similarity_index_to_basic_form_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldofstudy',
            options={'ordering': ['major_type']},
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='prefers_full_fund',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='prefers_half_fund',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='prefers_self_fund',
            field=models.BooleanField(default=False),
        ),
    ]
