# Generated by Django 2.2.3 on 2020-07-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_auto_20200726_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetailedinfo',
            old_name='marital_status',
            new_name='is_married',
        ),
    ]
