# Generated by Django 2.2.3 on 2020-07-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_auto_20200726_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='is_married',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='prefers_full_fund',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='prefers_half_fund',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='prefers_self_fund',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='MaritalStatus',
        ),
    ]
