# Generated by Django 2.2.3 on 2020-07-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_auto_20200726_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitythrough',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='wanttoapply',
            name='grade',
        ),
        migrations.DeleteModel(
            name='FormGrade',
        ),
    ]
