# Generated by Django 2.2.3 on 2020-07-26 16:30

from django.db import migrations
import enumfields.fields
import sNeeds.apps.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_auto_20200726_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationwhichauthor',
            name='basicformfield_ptr',
        ),
        migrations.AddField(
            model_name='universitythrough',
            name='grade',
            field=enumfields.fields.EnumField(default='کارشناسی', enum=sNeeds.apps.account.models.Grade, max_length=10),
        ),
        migrations.AddField(
            model_name='wanttoapply',
            name='grade',
            field=enumfields.fields.EnumField(default='کارشناسی', enum=sNeeds.apps.account.models.Grade, max_length=10),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=enumfields.fields.EnumField(default='ژورنالی', enum=sNeeds.apps.account.models.PublicationType, max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='which_author',
            field=enumfields.fields.EnumField(default='نویسنده اول', enum=sNeeds.apps.account.models.WhichAuthor, max_length=20),
        ),
        migrations.DeleteModel(
            name='PublicationType',
        ),
        migrations.DeleteModel(
            name='PublicationWhichAuthor',
        ),
    ]
