# Generated by Django 2.2.3 on 2020-07-26 15:21

from django.db import migrations
import enumfields.fields
import sNeeds.apps.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_auto_20200726_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='which_author',
            field=enumfields.fields.EnumField(enum=sNeeds.apps.account.models.WhichAuthor, max_length=10),
        ),
        migrations.DeleteModel(
            name='PublicationWhichAuthor',
        ),
    ]
