# Generated by Django 2.2.3 on 2020-07-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_auto_20200726_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wanttoapply',
            name='university',
        ),
        migrations.AddField(
            model_name='wanttoapply',
            name='university',
            field=models.ManyToManyField(blank=True, null=True, to='account.University'),
        ),
    ]
