# Generated by Django 2.2.3 on 2020-07-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_auto_20200726_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanttoapply',
            name='university',
            field=models.ManyToManyField(to='account.University'),
        ),
    ]
