# Generated by Django 2.2.3 on 2020-07-26 15:25

from django.db import migrations
import enumfields.fields
import sNeeds.apps.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_auto_20200726_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=enumfields.fields.EnumField(enum=sNeeds.apps.account.models.PublicationType, max_length=20),
        ),
        migrations.DeleteModel(
            name='PublicationType',
        ),
    ]
