# Generated by Django 2.2.3 on 2020-07-28 01:48

from django.db import migrations
import enumfields.fields
import sNeeds.apps.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_auto_20200726_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grecertificate',
            name='student_detailed_info',
        ),
        migrations.RemoveField(
            model_name='languagecertificatetype',
            name='basicformfield_ptr',
        ),
        migrations.RemoveField(
            model_name='languagecertificatetypethrough',
            name='certificate_type',
        ),
        migrations.RemoveField(
            model_name='languagecertificatetypethrough',
            name='student_detailed_info',
        ),
        migrations.RemoveField(
            model_name='paymentaffordability',
            name='basicformfield_ptr',
        ),
        migrations.RenameField(
            model_name='wanttoapply',
            old_name='university',
            new_name='universities',
        ),
        migrations.RemoveField(
            model_name='studentdetailedinfo',
            name='language_certificates',
        ),
        migrations.RemoveField(
            model_name='studentdetailedinfo',
            name='payment_affordability',
        ),
        migrations.AddField(
            model_name='publication',
            name='journal_reputation',
            field=enumfields.fields.EnumField(enum=sNeeds.apps.account.models.JournalReputation, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='gender',
            field=enumfields.fields.EnumField(default='آقا', enum=sNeeds.apps.account.models.Gender, max_length=10),
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='military_service_status',
            field=enumfields.fields.EnumField(default='گذرانده نشده', enum=sNeeds.apps.account.models.MilitaryServiceStatus, max_length=30),
        ),
        migrations.DeleteModel(
            name='GMATCertificate',
        ),
        migrations.DeleteModel(
            name='GRECertificate',
        ),
        migrations.DeleteModel(
            name='LanguageCertificateType',
        ),
        migrations.DeleteModel(
            name='LanguageCertificateTypeThrough',
        ),
        migrations.DeleteModel(
            name='PaymentAffordability',
        ),
    ]
