# Generated by Django 2.2.3 on 2020-07-28 01:49

from django.db import migrations
import enumfields.fields
import sNeeds.apps.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0058_auto_20200728_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='payment_affordability',
            field=enumfields.fields.EnumField(default='متوسط', enum=sNeeds.apps.account.models.PaymentAffordability, max_length=30),
        ),
    ]
