# Generated by Django 2.2.3 on 2020-07-28 03:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import sNeeds.apps.account.models
import sNeeds.apps.account.validators


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0059_studentdetailedinfo_payment_affordability'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', enumfields.fields.EnumField(default='IELTS', enum=sNeeds.apps.account.models.LanguageCertificateType, max_length=10)),
                ('student_detailed_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentDetailedInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Duolingo',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.LanguageCertificate')),
                ('overall', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(160)])),
                ('literacy', models.PositiveSmallIntegerField()),
                ('comprehension', models.PositiveSmallIntegerField()),
                ('conversation', models.PositiveSmallIntegerField()),
                ('production', models.PositiveSmallIntegerField()),
            ],
            bases=('account.languagecertificate',),
        ),
        migrations.CreateModel(
            name='GMATCertificate',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.LanguageCertificate')),
                ('analytical_writing_assessment', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.0)])),
                ('integrated_reasoning', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('quantitative_and_verbal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(51)])),
                ('total', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(800)])),
            ],
            bases=('account.languagecertificate',),
        ),
        migrations.CreateModel(
            name='GREGeneralCertificate',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.LanguageCertificate')),
                ('quantitative', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('verbal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('analytical_writing', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
            ],
            bases=('account.languagecertificate',),
        ),
        migrations.CreateModel(
            name='GREPhysicsCertificate',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.LanguageCertificate')),
                ('classical_mechanics', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('electromagnetism', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('quantum_mechanics', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
            ],
            bases=('account.languagecertificate',),
        ),
        migrations.CreateModel(
            name='GRESubjectCertificate',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.LanguageCertificate')),
                ('quantitative', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('verbal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('analytical_writing', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('total', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(990), sNeeds.apps.account.validators.ten_factor_validator])),
            ],
            bases=('account.languagecertificate',),
        ),
        migrations.CreateModel(
            name='RegularLanguageCertificate',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.LanguageCertificate')),
                ('speaking', models.DecimalField(decimal_places=2, max_digits=5)),
                ('listening', models.DecimalField(decimal_places=2, max_digits=5)),
                ('writing', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reading', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overall', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('account.languagecertificate',),
        ),
        migrations.CreateModel(
            name='GREBiologyCertificate',
            fields=[
                ('gresubjectcertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.GRESubjectCertificate')),
                ('cellular_and_molecular', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('organismal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('ecology_and_evolution', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
            ],
            bases=('account.gresubjectcertificate',),
        ),
        migrations.CreateModel(
            name='GREPsychologyCertificate',
            fields=[
                ('gresubjectcertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.GRESubjectCertificate')),
                ('biological', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('cognitive', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('social', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('developmental', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('clinical', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('measurement_or_methodology', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
            ],
            bases=('account.gresubjectcertificate',),
        ),
    ]
