# Generated by Django 2.2.3 on 2020-07-28 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_duolingo_gmatcertificate_grebiologycertificate_gregeneralcertificate_grephysicscertificate_grepsycho'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Duolingo',
            new_name='DuolingoCertificate',
        ),
    ]
