# Generated by Django 2.2.3 on 2020-07-28 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0061_auto_20200728_0827'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='universitythrough',
            unique_together={('student_detailed_info', 'grade')},
        ),
    ]
