# Generated by Django 2.2.3 on 2020-07-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_auto_20200728_0837'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='basicformfield',
            name='account_bas_name_se_1a51bc_gin',
        ),
        migrations.RemoveField(
            model_name='basicformfield',
            name='name_search',
        ),
    ]
