# Generated by Django 2.2.3 on 2020-07-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0063_auto_20200730_0007'),
    ]

    migration = '''
            DROP TRIGGER name_search_update ON account_basicformfield;
        '''

    reverse_migration = '''
            CREATE TRIGGER name_search_update BEFORE INSERT OR UPDATE
            ON account_basicformfield FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(name_search, 'pg_catalog.simple', name);

            -- Force triggers to run and populate the text_search column.
            UPDATE account_basicformfield set ID = ID;
        '''

    operations = [
        migrations.RunSQL(migration, reverse_migration)
    ]
