# Generated by Django 2.2.3 on 2020-07-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_auto_20200730_0008'),
    ]

    migration = '''
            DROP INDEX IF EXISTS trgm_idx CASCADE;
        '''

    reverse_migration = '''
            CREATE INDEX IF NOT EXISTS trgm_idx ON account_basicformfield USING GIST (name gist_trgm_ops);
        '''

    operations = [
        migrations.RunSQL(migration, reverse_migration)
    ]
