# Generated by Django 2.2.3 on 2020-07-30 12:09

from django.db import migrations
import enumfields.fields
import sNeeds.apps.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0065_auto_20200730_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagecertificate',
            name='certificate_type',
            field=enumfields.fields.EnumField(default='IELTS General', enum=sNeeds.apps.account.models.LanguageCertificateType, max_length=64),
        ),
    ]
