# Generated by Django 2.2.3 on 2020-07-30 13:44

from django.db import migrations
import enumfields.fields
import sNeeds.apps.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0066_auto_20200730_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagecertificate',
            name='certificate_type',
            field=enumfields.fields.EnumField(default='IELTS', enum=sNeeds.apps.account.models.LanguageCertificateType, help_text='Based on endpoint just some types are allowed to insert not all certificate types.', max_length=64),
        ),
    ]
