# Generated by Django 2.2.3 on 2020-08-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0067_auto_20200730_1814'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='languagecertificate',
            unique_together={('certificate_type', 'student_detailed_info')},
        ),
    ]
