# Generated by Django 2.2.3 on 2020-08-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0068_auto_20200806_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagecertificate',
            name='is_mock',
            field=models.BooleanField(default=True),
        ),
    ]
