# Generated by Django 2.2.3 on 2020-08-07 13:56

import django.core.validators
from django.db import migrations, models
import enumfields.fields
import sNeeds.apps.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0069_languagecertificate_is_mock'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='value',
            field=models.FloatField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal_reputation',
            field=enumfields.fields.EnumField(enum=sNeeds.apps.account.models.JournalReputation, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='which_author',
            field=enumfields.fields.EnumField(default='نویسنده اول', enum=sNeeds.apps.account.models.WhichAuthor, max_length=128),
        ),
    ]
