# Generated by Django 2.2.3 on 2020-08-11 08:30

from django.db import migrations
import enumfields.fields
import sNeeds.apps.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0070_auto_20200807_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdetailedinfo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='gender',
            field=enumfields.fields.EnumField(blank=True, default='آقا', enum=sNeeds.apps.account.models.Gender, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='military_service_status',
            field=enumfields.fields.EnumField(blank=True, default='گذرانده نشده', enum=sNeeds.apps.account.models.MilitaryServiceStatus, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='payment_affordability',
            field=enumfields.fields.EnumField(blank=True, default='متوسط', enum=sNeeds.apps.account.models.PaymentAffordability, max_length=30, null=True),
        ),
    ]
