# Generated by Django 2.2.3 on 2020-08-12 20:01

from django.db import migrations
import enumfields.fields
import sNeeds.apps.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0071_auto_20200811_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagecertificate',
            name='certificate_type',
            field=enumfields.fields.EnumField(default='IELTS General', enum=sNeeds.apps.account.models.LanguageCertificateType, help_text='Based on endpoint just some types are allowed to insert not all certificate types.', max_length=64),
        ),
    ]
