# Generated by Django 2.2.3 on 2020-08-17 17:06
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    def create_uuid(apps, schema_editor):
        StudentDetailedInfo = apps.get_model('account', 'StudentDetailedInfo')
        for sdi in StudentDetailedInfo.objects.all():
            sdi.uuid = uuid.uuid4()
            sdi.save()

    dependencies = [
        ('account', '0074_grephysicscertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(create_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=False, unique=True)
        )
    ]
