# Generated by Django 2.2.3 on 2020-08-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0075_auto_20200817_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanttoapply',
            name='student_detailed_info',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='student_detailed_info',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='universitythrough',
            name='student_detailed_info',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='languagecertificate',
            name='student_detailed_info',
            field=models.IntegerField(),
        ),
    ]
