# Generated by Django 2.2.3 on 2020-08-17 17:17
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0076_auto_20200817_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False
            ),
        ),
    ]
