# Generated by Django 2.2.3 on 2020-08-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0077_auto_20200817_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wanttoapply',
            old_name='student_detailed_info',
            new_name='student_detailed_info_old',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='student_detailed_info',
            new_name='student_detailed_info_old',
        ),
        migrations.RenameField(
            model_name='universitythrough',
            old_name='student_detailed_info',
            new_name='student_detailed_info_old',
        ),
        migrations.RenameField(
            model_name='languagecertificate',
            old_name='student_detailed_info',
            new_name='student_detailed_info_old',
        ),
    ]
