# Generated by Django 2.2.3 on 2020-08-17 17:19

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    def copy_WantToApply_uuid(apps, schema_editor):
        Model = apps.get_model('account', 'WantToApply')
        StudentDetailedInfo = apps.get_model('account', 'StudentDetailedInfo')
        student_detailed_info_uuid = StudentDetailedInfo.objects.filter(
            id=models.OuterRef('student_detailed_info_old')
        ).values_list('uuid')[:1]
        Model.objects.update(student_detailed_info=models.Subquery(student_detailed_info_uuid))

    def copy_Publication_uuid(apps, schema_editor):
        Model = apps.get_model('account', 'Publication')
        StudentDetailedInfo = apps.get_model('account', 'StudentDetailedInfo')
        student_detailed_info_uuid = StudentDetailedInfo.objects.filter(
            id=models.OuterRef('student_detailed_info_old')
        ).values_list('uuid')[:1]
        Model.objects.update(student_detailed_info=models.Subquery(student_detailed_info_uuid))

    def copy_UniversityThrough_uuid(apps, schema_editor):
        Model = apps.get_model('account', 'UniversityThrough')
        StudentDetailedInfo = apps.get_model('account', 'StudentDetailedInfo')
        student_detailed_info_uuid = StudentDetailedInfo.objects.filter(
            id=models.OuterRef('student_detailed_info_old')
        ).values_list('uuid')[:1]
        Model.objects.update(student_detailed_info=models.Subquery(student_detailed_info_uuid))

    def copy_LanguageCertificate_uuid(apps, schema_editor):
        Model = apps.get_model('account', 'LanguageCertificate')
        StudentDetailedInfo = apps.get_model('account', 'StudentDetailedInfo')
        student_detailed_info_uuid = StudentDetailedInfo.objects.filter(
            id=models.OuterRef('student_detailed_info_old')
        ).values_list('uuid')[:1]
        Model.objects.update(student_detailed_info=models.Subquery(student_detailed_info_uuid))

    dependencies = [
        ('account', '0078_auto_20200817_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanttoapply',
            name='student_detailed_info',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='account.StudentDetailedInfo'
            ),
        ),
        migrations.RunPython(
            copy_WantToApply_uuid,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AddField(
            model_name='publication',
            name='student_detailed_info',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='account.StudentDetailedInfo'
            ),
        ),
        migrations.RunPython(
            copy_Publication_uuid,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AddField(
            model_name='universitythrough',
            name='student_detailed_info',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='account.StudentDetailedInfo'
            ),
        ),
        migrations.RunPython(
            copy_UniversityThrough_uuid,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AddField(
            model_name='languagecertificate',
            name='student_detailed_info',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='account.StudentDetailedInfo'
            ),
        ),
        migrations.RunPython(
            copy_LanguageCertificate_uuid,
            reverse_code=migrations.RunPython.noop
        ),

    ]
