# Generated by Django 2.2.3 on 2020-08-17 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0079_auto_20200817_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdetailedinfo',
            options={},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='student_detailed_info_old',
        ),
        migrations.RemoveField(
            model_name='studentdetailedinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wanttoapply',
            name='student_detailed_info_old',
        ),
        migrations.AlterField(
            model_name='languagecertificate',
            name='is_mock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='languagecertificate',
            name='student_detailed_info',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.StudentDetailedInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='student_detailed_info',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.StudentDetailedInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='universitythrough',
            name='student_detailed_info',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.StudentDetailedInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wanttoapply',
            name='student_detailed_info',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.StudentDetailedInfo'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='languagecertificate',
            unique_together={('certificate_type', 'student_detailed_info')},
        ),
        migrations.AlterUniqueTogether(
            name='universitythrough',
            unique_together={('student_detailed_info', 'grade')},
        ),
        migrations.RemoveField(
            model_name='languagecertificate',
            name='student_detailed_info_old',
        ),
        migrations.RemoveField(
            model_name='universitythrough',
            name='student_detailed_info_old',
        ),
    ]
