# Generated by Django 2.2.3 on 2020-08-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0080_auto_20200817_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetailedinfo',
            old_name='uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='languagecertificate',
            name='student_detailed_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentDetailedInfo', to_field='id'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='student_detailed_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentDetailedInfo', to_field='id'),
        ),
        migrations.AlterField(
            model_name='universitythrough',
            name='student_detailed_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentDetailedInfo', to_field='id'),
        ),
        migrations.AlterField(
            model_name='wanttoapply',
            name='student_detailed_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentDetailedInfo', to_field='id'),
        ),
    ]
