# Generated by Django 2.2.3 on 2020-08-17 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0081_auto_20200817_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeModel',
            fields=[
                ('basicformfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.BasicFormField')),
            ],
            bases=('account.basicformfield',),
        ),
        migrations.AlterModelOptions(
            name='studentdetailedinfo',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='wanttoapply',
            name='country',
        ),
        migrations.RemoveField(
            model_name='wanttoapply',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='wanttoapply',
            name='major',
        ),
        migrations.RemoveField(
            model_name='wanttoapply',
            name='semester_year',
        ),
        migrations.AddField(
            model_name='wanttoapply',
            name='countries',
            field=models.ManyToManyField(to='account.Country'),
        ),
        migrations.AddField(
            model_name='wanttoapply',
            name='majors',
            field=models.ManyToManyField(to='account.FieldOfStudy'),
        ),
        migrations.AddField(
            model_name='wanttoapply',
            name='semester_years',
            field=models.ManyToManyField(to='account.StudentFormApplySemesterYear'),
        ),
        migrations.AddField(
            model_name='wanttoapply',
            name='grades',
            field=models.ManyToManyField(to='account.GradeModel'),
        ),
    ]
