# Generated by Django 2.2.3 on 2020-08-21 09:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sNeeds.apps.account.models
import sNeeds.apps.account.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0082_auto_20200818_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetailedInfoBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume', models.FileField(blank=True, null=True, upload_to=sNeeds.apps.account.models.get_student_resume_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), sNeeds.apps.account.validators.validate_resume_file_size])),
                ('related_work_experience', models.PositiveIntegerField(blank=True, help_text='In months', null=True)),
                ('academic_break', models.PositiveIntegerField(blank=True, help_text='In years', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('olympiad', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentdetailedinfo',
            name='academic_break',
        ),
        migrations.RemoveField(
            model_name='studentdetailedinfo',
            name='created',
        ),
        migrations.RemoveField(
            model_name='studentdetailedinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentdetailedinfo',
            name='olympiad',
        ),
        migrations.RemoveField(
            model_name='studentdetailedinfo',
            name='related_work_experience',
        ),
        migrations.RemoveField(
            model_name='studentdetailedinfo',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='studentdetailedinfo',
            name='universities',
        ),
        migrations.RemoveField(
            model_name='studentdetailedinfo',
            name='updated',
        ),
        migrations.AlterField(
            model_name='languagecertificate',
            name='student_detailed_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentDetailedInfoBase'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='student_detailed_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentDetailedInfoBase'),
        ),
        migrations.AlterField(
            model_name='universitythrough',
            name='student_detailed_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentDetailedInfoBase'),
        ),
        migrations.AlterField(
            model_name='wanttoapply',
            name='student_detailed_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.StudentDetailedInfoBase'),
        ),
        migrations.AddField(
            model_name='studentdetailedinfobase',
            name='universities',
            field=models.ManyToManyField(through='account.UniversityThrough', to='account.University'),
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='studentdetailedinfobase_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.StudentDetailedInfoBase'),
            preserve_default=False,
        ),
    ]
