# Generated by Django 2.2.3 on 2020-08-21 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0083_auto_20200821_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedStudentDetailedInfo',
            fields=[
                ('studentdetailedinfobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.StudentDetailedInfoBase')),
            ],
            bases=('account.studentdetailedinfobase',),
        ),
    ]
