# Generated by Django 2.2.3 on 2020-08-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0084_appliedstudentdetailedinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppliedStudentDetailedInfo',
        ),
    ]
