# Generated by Django 2.2.3 on 2020-08-21 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0085_delete_appliedstudentdetailedinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanttoapply',
            name='student_detailed_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='want_to_apply', to='account.StudentDetailedInfoBase'),
        ),
    ]
