# Generated by Django 2.2.3 on 2020-08-24 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0086_auto_20200821_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanttoapply',
            name='student_detailed_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='want_to_apply', to='account.StudentDetailedInfoBase'),
        ),
    ]
