# Generated by Django 2.2.3 on 2020-08-28 07:02

from django.db import migrations, models
from django.db.models import F


def migrate_field_of_study(apps, schema_editor):
    FieldOfStudy = apps.get_model("account", "FieldOfStudy")
    FieldOfStudy.objects.all().update(
        search_name=F('name')
    )


def migrate_university(apps, schema_editor):
    University = apps.get_model("account", "University")
    University.objects.all().update(
        search_name=F('name')
    )


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0087_auto_20200824_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudy',
            name='search_name',
            field=models.CharField(null=True, max_length=1024, unique=True),
        ),

        migrations.RunPython(migrate_field_of_study),

        migrations.AddField(
            model_name='university',
            name='search_name',
            field=models.CharField(null=True, max_length=1024, unique=True),
        ),

        migrations.RunPython(migrate_university)
    ]
