# Generated by Django 2.2.3 on 2020-08-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0088_auto_20200828_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldofstudy',
            name='search_name',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='search_name',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
