# Generated by Django 2.2.3 on 2020-08-28 07:36

from django.db import migrations, models
from django.db.models import F


def migrate_country(apps, schema_editor):
    Country = apps.get_model("account", "Country")
    Country.objects.all().update(
        search_name=F('name')
    )


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0089_auto_20200828_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='search_name',
            field=models.CharField(null=True, max_length=256, unique=True),
        ),

        migrations.RunPython(migrate_country),

    ]
