# Generated by Django 2.2.3 on 2020-09-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0090_country_search_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='search_name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
