# Generated by Django 2.2.3 on 2020-09-19 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0092_auto_20200901_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagecertificate',
            name='value',
            field=models.FloatField(default=0.5, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
    ]
