# Generated by Django 2.2.3 on 2020-09-22 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0093_languagecertificate_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitythrough',
            name='value',
            field=models.FloatField(editable=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='languagecertificate',
            name='value',
            field=models.FloatField(editable=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
