# Generated by Django 2.2.3 on 2020-09-27 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0094_auto_20200922_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='value',
            field=models.FloatField(editable=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
