# Generated by Django 2.2.3 on 2020-09-27 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0095_studentdetailedinfo_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='rank',
            field=models.IntegerField(default=12, editable=False, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
