# Generated by Django 2.2.3 on 2020-09-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0096_studentdetailedinfo_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdetailedinfo',
            options={'ordering': ['-created']},
        ),
    ]
