# TOEFL

TOEFL_AP_START = 110
TOEFL_A_START = 105
TOEFL_A_END = 110
TOEFL_BP_START = 100
TOEFL_BP_END = 105
TOEFL_B_START = 92
TOEFL_B_END = 100
TOEFL_C_START = 78
TOEFL_C_END = 92
TOEFL_D_END = 78

TOEFL_AP_VALUE = 1
TOEFL_A_VALUE = 0.9
TOEFL_BP_VALUE = 0.8
TOEFL_B_VALUE = 0.7
TOEFL_C_VALUE = 0.3
TOEFL_D_VALUE = 0

# IELTS

IELTS_AP_START = 8
IELTS_A_START = 7.5
IELTS_A_END = 8
IELTS_BP_START = 7
IELTS_BP_END = 7.5
IELTS_B_START = 6.5
IELTS_B_END = 7
IELTS_C_START = 6
IELTS_C_END = 6.5
IELTS_D_END = 6

IELTS_AP_VALUE = 1
IELTS_A_VALUE = 0.9
IELTS_BP_VALUE = 0.8
IELTS_B_VALUE = 0.7
IELTS_C_VALUE = 0.3
IELTS_D_VALUE = 0


# Universities

GREATE_UNIVERSITY_RANK = 100
GOOD_UNIVERSITY_RANK = 400
AVERAGE_UNIVERSITY_RANK = 800
BAD_UNIVERSITY_RANK = 1200

