# Generated by Django 3.1.1 on 2021-01-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0033_auto_20210106_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetailedinfobase',
            old_name='id',
            new_name='old_id',
        ),
    ]
