# Generated by Django 3.1.1 on 2021-01-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0034_auto_20210106_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetailedinfobase',
            old_name='new_id',
            new_name='id',
        ),
    ]
