# Generated by Django 3.1.1 on 2021-01-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0035_auto_20210106_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanttoapply',
            name='student_detailed_info',
            field=models.UUIDField(),
        ),
    ]
