# Generated by Django 3.1.1 on 2021-01-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0036_auto_20210106_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wanttoapply',
            old_name='student_detailed_info',
            new_name='student_detailed_info_old',
        ),
    ]
