# Generated by Django 2.2.3 on 2020-07-26 15:15

from django.db import migrations
import enumfields.fields
import sNeeds.apps.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_auto_20200726_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitythrough',
            name='grade',
            field=enumfields.fields.EnumField(null=True, default=None, enum=sNeeds.apps.account.models.Grade, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wanttoapply',
            name='grade',
            field=enumfields.fields.EnumField(null=True, default=None, enum=sNeeds.apps.account.models.Grade, max_length=10),
            preserve_default=False,
        ),
    ]
