# Generated by Django 2.2.3 on 2020-07-29 18:33

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_auto_20200728_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='name_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
