# Generated by Django 2.2.3 on 2020-07-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0063_university_name_search'),
    ]

    migration = '''
            CREATE TRIGGER account_university_name_search_update BEFORE INSERT OR UPDATE
            ON account_university FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(name_search, 'pg_catalog.simple', name);

            -- Force triggers to run and populate the text_search column.
            UPDATE account_university set ID = ID;
        '''

    reverse_migration = '''
            DROP TRIGGER account_university_name_search_update ON account_university;
        '''

    operations = [
        migrations.RunSQL(migration, reverse_migration)
    ]
