# Generated by Django 2.2.3 on 2020-07-29 18:36
from django.contrib.postgres.search import SearchVector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_auto_20200729_2303'),
    ]

    def forwards_func(apps, schema_editor):
        # We get the model from the versioned app registry;
        # if we directly import it, it'll be the wrong version
        University = apps.get_model("account", "university")
        db_alias = schema_editor.connection.alias
        University.objects.using(db_alias).update(name_search=SearchVector('name'))

    def reverse_func(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
