# Generated by Django 2.2.3 on 2020-07-29 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0065_auto_20200729_2306'),
    ]
    migration = '''
    CREATE INDEX IF NOT EXISTS account_university_name_search_idx ON account_university USING GIN (name_search);
    '''

    reverse_migration = '''
                DROP INDEX IF EXISTS account_university_name_search_idx CASCADE;
            '''

    operations = [
        migrations.RunSQL(migration, reverse_migration)
    ]
