# Generated by Django 2.2.3 on 2020-08-12 20:19

from django.db import migrations
from ..models import LanguageCertificateType

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0072_auto_20200813_0031'),
    ]

    def forwards_func(apps, schema_editor):
        # We get the model from the versioned app registry;
        # if we directly import it, it'll be the wrong version
        LanguageCertificate = apps.get_model("account", "")
        db_alias = schema_editor.connection.alias
        LanguageCertificate.objects.using(db_alias).raw(certificate_type=LanguageCertificateType.I).delete()

    def reverse_func(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
