# Generated by Django 3.1.1 on 2021-02-01 06:33

import abroadin.apps.data.account.validators
import abroadin.base.mixins.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PH.D', 'PH.D'), ('Post Doc', 'Post Doc')], default='Bachelor', max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('certificate_type', models.CharField(choices=[('IELTS General', 'IELTS General'), ('IELTS Academic', 'IELTS Academic'), ('TOEFL', 'TOEFL'), ('GMAT', 'GMAT'), ('GRE General', 'GRE General'), ('GRE Chemistry', 'GRE Chemistry'), ('GRE Mathematics', 'GRE Mathematics'), ('GRE Literature', 'GRE Literature'), ('GRE Biology', 'GRE Biology'), ('GRE Physics', 'GRE Physics'), ('GRE Psychology', 'GRE Psychology'), ('Duolingo', 'Duolingo')], default='TOEFL', help_text='Based on endpoint just some types are allowed to insert not all certificate types.', max_length=64)),
                ('is_mock', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_certificates', to='contenttypes.contenttype')),
                ('real_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('certificate_type', 'content_type', 'object_id')},
            },
            bases=(abroadin.base.mixins.validators.GenericForeignkeyUniqueTogetherValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SemesterYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(help_text='In Gregorian', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('semester', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=64)),
            ],
            options={
                'ordering': ['year', 'semester'],
            },
        ),
        migrations.CreateModel(
            name='DuolingoCertificate',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applydata.languagecertificate')),
                ('overall', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(160)])),
                ('literacy', models.PositiveSmallIntegerField()),
                ('comprehension', models.PositiveSmallIntegerField()),
                ('conversation', models.PositiveSmallIntegerField()),
                ('production', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('applydata.languagecertificate',),
        ),
        migrations.CreateModel(
            name='GMATCertificate',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applydata.languagecertificate')),
                ('analytical_writing_assessment', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.0)])),
                ('integrated_reasoning', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('quantitative_and_verbal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(51)])),
                ('total', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(800)])),
            ],
            options={
                'abstract': False,
            },
            bases=('applydata.languagecertificate',),
        ),
        migrations.CreateModel(
            name='GREGeneralCertificate',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applydata.languagecertificate')),
                ('quantitative', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('verbal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('analytical_writing', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
            ],
            options={
                'abstract': False,
            },
            bases=('applydata.languagecertificate',),
        ),
        migrations.CreateModel(
            name='GRESubjectCertificate',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applydata.languagecertificate')),
                ('quantitative', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('verbal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('analytical_writing', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('total', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(990), abroadin.apps.data.account.validators.ten_factor_validator])),
            ],
            options={
                'abstract': False,
            },
            bases=('applydata.languagecertificate',),
        ),
        migrations.CreateModel(
            name='RegularLanguageCertificate',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applydata.languagecertificate')),
                ('speaking', models.DecimalField(decimal_places=1, help_text=' IELTS speaking 0 to 9 and TOEFL speaking 0 to 30', max_digits=4)),
                ('listening', models.DecimalField(decimal_places=1, help_text=' IELTS listening 0 to 9 and TOEFL listening 0 to 30', max_digits=4)),
                ('writing', models.DecimalField(decimal_places=1, help_text=' IELTS writing 0 to 9 and TOEFL writing 0 to 30', max_digits=4)),
                ('reading', models.DecimalField(decimal_places=1, help_text=' IELTS reading 0 to 9 and TOEFL reading 0 to 30', max_digits=4)),
                ('overall', models.DecimalField(decimal_places=1, help_text=' IELTS overall 1 to 9 and TOEFL overall 0 to 120', max_digits=4)),
            ],
            options={
                'abstract': False,
            },
            bases=('applydata.languagecertificate',),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=512)),
                ('publish_year', models.SmallIntegerField(help_text='In Gregorian', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('which_author', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth or more', 'Fourth or more')], default='Fourth or more', max_length=128)),
                ('type', models.CharField(choices=[('Journal', 'Journal'), ('Conference', 'Conference')], default='Journal', max_length=20)),
                ('journal_reputation', models.CharField(choices=[('One to three', 'One to three'), ('Four to ten', 'Four to ten'), ('Above ten', 'Above ten')], max_length=128)),
                ('value', models.FloatField(editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('grade', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PH.D', 'PH.D'), ('Post Doc', 'Post Doc')], default='Bachelor', max_length=128)),
                ('graduate_in', models.SmallIntegerField(help_text='In Gregorian', validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2100)])),
                ('thesis_title', models.CharField(blank=True, max_length=512, null=True)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('value', models.FloatField(editable=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.major')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.university')),
            ],
            bases=(abroadin.base.mixins.validators.GenericForeignkeyUniqueTogetherValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GREBiologyCertificate',
            fields=[
                ('gresubjectcertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applydata.gresubjectcertificate')),
                ('cellular_and_molecular', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('organismal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('ecology_and_evolution', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
            ],
            options={
                'abstract': False,
            },
            bases=('applydata.gresubjectcertificate',),
        ),
        migrations.CreateModel(
            name='GREPhysicsCertificate',
            fields=[
                ('gresubjectcertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applydata.gresubjectcertificate')),
                ('classical_mechanics', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('electromagnetism', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('quantum_mechanics', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
            ],
            options={
                'abstract': False,
            },
            bases=('applydata.gresubjectcertificate',),
        ),
        migrations.CreateModel(
            name='GREPsychologyCertificate',
            fields=[
                ('gresubjectcertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applydata.gresubjectcertificate')),
                ('biological', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('cognitive', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('social', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('developmental', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('clinical', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('measurement_or_methodology', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
            ],
            options={
                'abstract': False,
            },
            bases=('applydata.gresubjectcertificate',),
        ),
    ]
