# Generated by Django 3.1.1 on 2020-12-27 09:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0009_auto_20201222_1050'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PH.D', 'PH.D'), ('Post Doc', 'Post Doc')], default='Bachelor', max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(help_text='In Gregorian', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('semester', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=64)),
            ],
            options={
                'ordering': ['year', 'semester'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=512)),
                ('publish_year', models.SmallIntegerField(help_text='In Gregorian', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('which_author', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth or more', 'Fourth or more')], default='Fourth or more', max_length=128)),
                ('type', models.CharField(choices=[('Journal', 'Journal'), ('Conference', 'Conference')], default='Journal', max_length=20)),
                ('journal_reputation', models.CharField(choices=[('One to three', 'One to three'), ('Four to ten', 'Four to ten'), ('Above ten', 'Above ten')], max_length=128)),
                ('value', models.FloatField(editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('certificate_type', models.CharField(choices=[('IELTS General', 'IELTS General'), ('IELTS Academic', 'IELTS Academic'), ('TOEFL', 'TOEFL'), ('GMAT', 'GMAT'), ('GRE General', 'GRE General'), ('GRE Chemistry', 'GRE Chemistry'), ('GRE Mathematics', 'GRE Mathematics'), ('GRE Literature', 'GRE Literature'), ('GRE Biology', 'GRE Biology'), ('GRE Physics', 'GRE Physics'), ('GRE Psychology', 'GRE Psychology'), ('Duolingo', 'Duolingo')], default='TOEFL', help_text='Based on endpoint just some types are allowed to insert not all certificate types.', max_length=64)),
                ('is_mock', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('certificate_type', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('grade', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PH.D', 'PH.D'), ('Post Doc', 'Post Doc')], default='Bachelor', max_length=128)),
                ('graduate_in', models.SmallIntegerField(help_text='In Gregorian', validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2100)])),
                ('thesis_title', models.CharField(blank=True, max_length=512, null=True)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('value', models.FloatField(editable=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.major')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.university')),
            ],
            options={
                'unique_together': {('grade',)},
            },
        ),
    ]
