# Generated by Django 3.1.1 on 2020-12-25 22:40

import abroadin.apps.data.account.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applyData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuolingoCertificate',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applyData.languagecertificate')),
                ('overall', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(160)])),
                ('literacy', models.PositiveSmallIntegerField()),
                ('comprehension', models.PositiveSmallIntegerField()),
                ('conversation', models.PositiveSmallIntegerField()),
                ('production', models.PositiveSmallIntegerField()),
            ],
            bases=('applyData.languagecertificate',),
        ),
        migrations.CreateModel(
            name='GMATCertificate',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applyData.languagecertificate')),
                ('analytical_writing_assessment', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.0)])),
                ('integrated_reasoning', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('quantitative_and_verbal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(51)])),
                ('total', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(800)])),
            ],
            bases=('applyData.languagecertificate',),
        ),
        migrations.CreateModel(
            name='GREGeneralCertificate',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applyData.languagecertificate')),
                ('quantitative', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('verbal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('analytical_writing', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
            ],
            bases=('applyData.languagecertificate',),
        ),
        migrations.CreateModel(
            name='GRESubjectCertificate',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applyData.languagecertificate')),
                ('quantitative', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('verbal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('analytical_writing', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('total', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(990), abroadin.apps.data.account.validators.ten_factor_validator])),
            ],
            bases=('applyData.languagecertificate',),
        ),
        migrations.CreateModel(
            name='RegularLanguageCertificate',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applyData.languagecertificate')),
                ('speaking', models.DecimalField(decimal_places=1, help_text=' IELTS speaking 0 to 9 and TOEFL speaking 0 to 30', max_digits=4)),
                ('listening', models.DecimalField(decimal_places=1, help_text=' IELTS listening 0 to 9 and TOEFL listening 0 to 30', max_digits=4)),
                ('writing', models.DecimalField(decimal_places=1, help_text=' IELTS writing 0 to 9 and TOEFL writing 0 to 30', max_digits=4)),
                ('reading', models.DecimalField(decimal_places=1, help_text=' IELTS reading 0 to 9 and TOEFL reading 0 to 30', max_digits=4)),
                ('overall', models.DecimalField(decimal_places=1, help_text=' IELTS overall 1 to 9 and TOEFL overall 0 to 120', max_digits=4)),
            ],
            bases=('applyData.languagecertificate',),
        ),
        migrations.CreateModel(
            name='GREBiologyCertificate',
            fields=[
                ('gresubjectcertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applyData.gresubjectcertificate')),
                ('cellular_and_molecular', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('organismal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('ecology_and_evolution', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
            ],
            bases=('applyData.gresubjectcertificate',),
        ),
        migrations.CreateModel(
            name='GREPhysicsCertificate',
            fields=[
                ('gresubjectcertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applyData.gresubjectcertificate')),
                ('classical_mechanics', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('electromagnetism', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('quantum_mechanics', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
            ],
            bases=('applyData.gresubjectcertificate',),
        ),
        migrations.CreateModel(
            name='GREPsychologyCertificate',
            fields=[
                ('gresubjectcertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applyData.gresubjectcertificate')),
                ('biological', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('cognitive', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('social', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('developmental', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('clinical', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('measurement_or_methodology', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
            ],
            bases=('applyData.gresubjectcertificate',),
        ),
    ]
