# Generated by Django 3.1.1 on 2021-04-18 13:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globaldata', '0001_initial'),
        ('applydata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='globaldata.major'),
        ),
        migrations.AddField(
            model_name='education',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='globaldata.university'),
        ),
        migrations.CreateModel(
            name='GREBiologyCertificate',
            fields=[
                ('gresubjectcertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applydata.gresubjectcertificate')),
                ('cellular_and_molecular', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('organismal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('ecology_and_evolution', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
            ],
            options={
                'abstract': False,
            },
            bases=('applydata.gresubjectcertificate',),
        ),
        migrations.CreateModel(
            name='GREPhysicsCertificate',
            fields=[
                ('gresubjectcertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applydata.gresubjectcertificate')),
                ('classical_mechanics', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('electromagnetism', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('quantum_mechanics', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
            ],
            options={
                'abstract': False,
            },
            bases=('applydata.gresubjectcertificate',),
        ),
        migrations.CreateModel(
            name='GREPsychologyCertificate',
            fields=[
                ('gresubjectcertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applydata.gresubjectcertificate')),
                ('biological', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('cognitive', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('social', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('developmental', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('clinical', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('measurement_or_methodology', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
            ],
            options={
                'abstract': False,
            },
            bases=('applydata.gresubjectcertificate',),
        ),
        migrations.AlterUniqueTogether(
            name='languagecertificate',
            unique_together={('certificate_type', 'content_type', 'object_id')},
        ),
    ]
