# Generated by Django 3.1.1 on 2021-01-07 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applydata', '0002_duolingocertificate_gmatcertificate_grebiologycertificate_gregeneralcertificate_grephysicscertificat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='education',
            unique_together=set(),
        ),
    ]
