# Generated by Django 3.1.1 on 2021-01-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applydata', '0003_auto_20210108_0005'),
        ('form', '0042_auto_20210107_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='object_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='languagecertificate',
            name='object_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='publication',
            name='object_id',
            field=models.CharField(max_length=40),
        ),
    ]
