# Generated by Django 3.1.1 on 2021-01-15 12:15

from django.db import migrations, models
from django.db.models import PositiveIntegerField
from django.db.models.functions import Cast

from abroadin.base.models.migrations.decortaors import flex_run_python_decorator


def fill_new_object_id(apps, schema_editor, app_name, model_name):
    Model = apps.get_model(app_name, model_name)
    Model.objects.all().update(new_object_id=Cast('object_id', output_field=PositiveIntegerField()))


class Migration(migrations.Migration):

    dependencies = [
        ('applydata', '0004_auto_20210107_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='new_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='languagecertificate',
            name='new_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='new_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.RunPython(code=flex_run_python_decorator(fill_new_object_id, 'applydata', 'education'),
                             reverse_code=migrations.RunPython.noop),
        migrations.RunPython(code=flex_run_python_decorator(fill_new_object_id, 'applydata', 'languagecertificate'),
                             reverse_code=migrations.RunPython.noop),
        migrations.RunPython(code=flex_run_python_decorator(fill_new_object_id, 'applydata', 'publication'),
                             reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='education',
            name='new_object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='languagecertificate',
            name='new_object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='new_object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
