# Generated by Django 3.1.1 on 2021-01-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('applydata', '0005_education_new_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='object_id',
        ),
        migrations.AlterUniqueTogether(
            name='languagecertificate',
            unique_together={('certificate_type', 'content_type', 'new_object_id')},
        ),
        migrations.RemoveField(
            model_name='languagecertificate',
            name='object_id',
        ),
    ]
