# Generated by Django 3.1.1 on 2021-01-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('applydata', '0006_auto_20210115_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='new_object_id',
            new_name='object_id',
        ),
        migrations.RenameField(
            model_name='languagecertificate',
            old_name='new_object_id',
            new_name='object_id',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='new_object_id',
            new_name='object_id',
        ),
        migrations.AlterUniqueTogether(
            name='languagecertificate',
            unique_together={('certificate_type', 'content_type', 'object_id')},
        ),
    ]
