# Generated by Django 3.1.1 on 2021-01-24 07:18
from django.db import migrations, models
import django.db.models.deletion


def set_language_certificates_real_type(apps, schema_editor):
    class LanguageCertificateType(models.TextChoices):
        IELTS_GENERAL = 'IELTS General', 'IELTS General'
        IELTS_ACADEMIC = 'IELTS Academic', 'IELTS Academic'
        TOEFL = 'TOEFL', 'TOEFL'
        GMAT = 'GMAT', 'GMAT'
        GRE_GENERAL = 'GRE General', 'GRE General'
        GRE_CHEMISTRY = 'GRE Chemistry', 'GRE Chemistry'
        GRE_MATHEMATICS = 'GRE Mathematics', 'GRE Mathematics'
        GRE_LITERATURE = 'GRE Literature', 'GRE Literature'
        GRE_BIOLOGY = 'GRE Biology', 'GRE Biology'
        GRE_PHYSICS = 'GRE Physics', 'GRE Physics'
        GRE_PSYCHOLOGY = 'GRE Psychology', 'GRE Psychology'
        DUOLINGO = 'Duolingo', 'Duolingo'


    LanguageCertificate = apps.get_model('applydata', 'languagecertificate')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    qs = LanguageCertificate.objects.all()
    LCType = LanguageCertificateType

    for obj in qs:
        if obj.certificate_type in [LCType.TOEFL, LCType.IELTS_GENERAL, LCType.IELTS_ACADEMIC]:
            obj.real_type = ContentType.objects.get(app_label="applydata", model="regularlanguagecertificate")

        elif obj.certificate_type in [LCType.GMAT]:
            obj.real_type = ContentType.objects.get(app_label="applydata", model="gmatcertificate")

        elif obj.certificate_type in [LCType.GRE_GENERAL]:
            obj.real_type = ContentType.objects.get(app_label="applydata", model="gregeneralcertificate")

        elif obj.certificate_type in [LCType.GRE_CHEMISTRY, LCType.GRE_LITERATURE, LCType.GRE_MATHEMATICS]:
            obj.real_type = ContentType.objects.get(app_label="applydata", model="gresubjectcertificate")

        elif obj.certificate_type in [LCType.GRE_BIOLOGY]:
            obj.real_type = ContentType.objects.get(app_label="applydata", model="grebiologycertificate")

        elif obj.certificate_type in [LCType.GRE_PHYSICS]:
            obj.real_type = ContentType.objects.get(app_label="applydata", model="grephysicscertificate")

        elif obj.certificate_type in [LCType.GRE_PSYCHOLOGY]:
            obj.real_type = ContentType.objects.get(app_label="applydata", model="grepsychologycertificate")

        elif obj.certificate_type in [LCType.DUOLINGO]:
            obj.real_type = ContentType.objects.get(app_label="applydata", model="duolingocertificate")

        else:
            raise Exception("Wrong type in real type, maybe one app_label is incorrect")

        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('applydata', '0007_auto_20210115_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagecertificate',
            name='real_type',
            field=models.ForeignKey(null=True, editable=False, on_delete=django.db.models.deletion.PROTECT,
                                    to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='languagecertificate',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_certificates',
                                    to='contenttypes.contenttype'),
        ),
        migrations.RunPython(code=set_language_certificates_real_type),
        migrations.AlterField(
            model_name='languagecertificate',
            name='real_type',
            field=models.ForeignKey(null=False, editable=False,
                                    on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
    ]
