# Generated by Django 3.1.1 on 2020-12-25 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applyData', '0002_duolingocertificate_gmatcertificate_grebiologycertificate_gregeneralcertificate_grephysicscertificat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=255)),
                ('latest_degree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applyData.education')),
            ],
        ),
    ]
