# Generated by Django 3.1.1 on 2020-12-25 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applyData', '0002_duolingocertificate_gmatcertificate_grebiologycertificate_gregeneralcertificate_grephysicscertificat'),
        ('applyProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyprofile',
            name='latest_degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applyData.education'),
        ),
    ]
