# Generated by Django 3.1.1 on 2021-02-01 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('title', models.CharField(choices=[('Grade Point Average', 'Grade Point Average'), ('Publications Count', 'Publications Count'), ('Publication Type', 'Publication Type'), ('Publications Score', 'Publications Score'), ('Publication Impact Factor', 'Publication Impact Factor'), ('Powerful Recommendation', 'Powerful Recommendation'), ('Olympiad', 'Olympiad'), ('Related Work Experience', 'Related Work Experience'), ('Toefl', 'Toefl'), ('Ielts', 'Ielts'), ('GMAT', 'GMAT'), ('GRE General Writing', 'GRE General Writing'), ('GRE General Quantitative And Verbal', 'GRE General Quantitative And Verbal'), ('GRE Subject Total', 'GRE Subject Total'), ('Duolingo', 'Duolingo')], max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChartItemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('count', models.FloatField(default=0)),
                ('label_rank', models.FloatField(default=0)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.chart')),
            ],
            options={
                'ordering': ['chart', 'label_rank'],
                'unique_together': {('label', 'chart')},
            },
        ),
    ]
