# Generated by Django 3.1.1 on 2020-10-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0002_auto_20201004_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartitemdata',
            options={'ordering': ['chart', 'label_rank']},
        ),
        migrations.AddField(
            model_name='chartitemdata',
            name='label_rank',
            field=models.FloatField(default=0),
        ),
    ]
