# Generated by Django 3.1.1 on 2021-02-01 06:33

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.notification')),
                ('email', models.EmailField(max_length=254)),
                ('data_json', jsonfield.fields.JSONField()),
            ],
            bases=('notifications.notification',),
        ),
        migrations.CreateModel(
            name='SoldTimeSlotChangedEmailNotification',
            fields=[
                ('emailnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.emailnotification')),
                ('sold_time_slot_id', models.PositiveIntegerField()),
            ],
            bases=('notifications.emailnotification',),
        ),
        migrations.CreateModel(
            name='SoldTimeSlotReminderEmailNotification',
            fields=[
                ('emailnotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.emailnotification')),
                ('sold_time_slot_id', models.PositiveIntegerField()),
            ],
            bases=('notifications.emailnotification',),
        ),
    ]
