# Generated by Django 3.1.1 on 2021-02-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldtimeslotreminderemailnotification',
            name='emailnotification_ptr',
        ),
        migrations.DeleteModel(
            name='SoldTimeSlotChangedEmailNotification',
        ),
        migrations.DeleteModel(
            name='SoldTimeSlotReminderEmailNotification',
        ),
    ]
