# Generated by Django 3.1.1 on 2021-04-11 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applydata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('grade_text', models.CharField(blank=True, max_length=1024, null=True)),
                ('min_length', models.IntegerField()),
                ('max_length', models.IntegerField()),
                ('coop_length', models.IntegerField(default=0)),
                ('length_breakdown', models.CharField(blank=True, max_length=1024, null=True)),
                ('tuition', models.IntegerField()),
                ('application_fee', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applydata.grade')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramOtherFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('fee', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramOtherRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_text', models.CharField(blank=True, max_length=1024, null=True)),
                ('min_gpa', models.FloatField()),
                ('english_score_required', models.BooleanField()),
                ('min_duolingo_score', models.FloatField()),
                ('min_toefl_reading', models.FloatField()),
                ('min_toefl_writing', models.FloatField()),
                ('min_toefl_listening', models.FloatField()),
                ('min_toefl_speaking', models.FloatField()),
                ('min_toefl_total', models.FloatField()),
                ('min_ielts_reading', models.FloatField()),
                ('min_ielts_writing', models.FloatField()),
                ('min_ielts_listening', models.FloatField()),
                ('min_ielts_speaking', models.FloatField()),
                ('min_ielts_average', models.FloatField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applydata.grade')),
                ('other_requirements', models.ManyToManyField(to='programs.ProgramOtherRequirement')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramIntake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=256)),
                ('start_date', models.DateField()),
                ('open_date', models.DateField()),
                ('deadline', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='other_fees',
            field=models.ManyToManyField(to='programs.ProgramOtherFee'),
        ),
    ]
