# Generated by Django 3.1.1 on 2021-04-13 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programrequirement',
            name='program',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='programs.program'),
            preserve_default=False,
        ),
    ]
