# Generated by Django 3.1.1 on 2021-01-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultantDepositInfo',
        ),
    ]
