# Generated by Django 3.1.1 on 2021-01-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_delete_consultantdepositinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypayment',
            name='authority',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
