# Generated by Django 3.1.1 on 2021-02-01 06:33

import abroadin.apps.store.discounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultants', '0002_auto_20210201_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlotSaleNumberDiscount',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('discount', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('code', abroadin.apps.store.discounts.models.CICharField(blank=True, help_text='If want to populate automatically, Leave this field blank. Otherwise enter code', max_length=128, unique=True)),
                ('use_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('creator', models.CharField(choices=[('consultant', 'Consultant'), ('admin', 'Admin')], default='admin', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('consultants', models.ManyToManyField(blank=True, to='consultants.ConsultantProfile')),
            ],
        ),
    ]
