# Generated by Django 3.1.1 on 2020-10-04 10:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import abroadin.apps.store.discounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storeBase', '0001_initial'),
        ('carts', '0002_auto_20201004_1347'),
        ('consultants', '0002_auto_20201004_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotSaleNumberDiscount',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('discount', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('code', abroadin.apps.store.discounts.models.CICharField(blank=True, help_text='If want to populate automatically, Leave this field blank. Otherwise enter code', max_length=128, unique=True)),
                ('use_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('creator', models.CharField(choices=[('consultant', 'Consultant'), ('admin', 'Admin')], default='admin', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('consultants', models.ManyToManyField(blank=True, to='consultants.ConsultantProfile')),
                ('products', models.ManyToManyField(blank=True, to='storeBase.Product')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.discount')),
            ],
            options={
                'unique_together': {('cart', 'discount')},
            },
        ),
    ]
