# Generated by Django 2.2.3 on 2020-09-01 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0091_auto_20200901_1430'),
        ('similarApply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Country')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.GradeModel')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.FieldOfStudy')),
                ('semester_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.StudentFormApplySemesterYear')),
                ('student_detailed_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applied_to', to='similarApply.AppliedStudentDetailedInfo')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.University')),
            ],
        ),
    ]
