# Generated by Django 2.2.3 on 2020-09-02 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similarApply', '0002_appliedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedto',
            name='accepted',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appliedto',
            name='comment',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appliedto',
            name='fund',
            field=models.IntegerField(default=1, help_text='In Dollars', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
            preserve_default=False,
        ),
    ]
