# Generated by Django 2.2.3 on 2020-09-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similarApply', '0003_auto_20200902_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedto',
            name='fund',
            field=models.IntegerField(help_text='In Dollars'),
        ),
    ]
