# Generated by Django 2.2.3 on 2020-09-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('similarApply', '0004_auto_20200905_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedto',
            old_name='student_detailed_info',
            new_name='applied_student_detailed_info',
        ),
    ]
