# Generated by Django 2.2.3 on 2020-09-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similarApply', '0005_auto_20200906_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedto',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='appliedto',
            name='fund',
            field=models.IntegerField(blank=True, help_text='In Dollars', null=True),
        ),
    ]
