# Generated by Django 2.2.3 on 2020-09-28 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('similarApply', '0006_auto_20200915_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedto',
            name='applied_student_detailed_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_to', to='similarApply.AppliedStudentDetailedInfo'),
        ),
    ]
