# Generated by Django 3.1.1 on 2020-10-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201004_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='major',
            name='search_name',
            field=models.CharField(max_length=1024),
        ),
    ]
