# Generated by Django 3.1.1 on 2020-10-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201013_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='rank',
            field=models.PositiveIntegerField(default=1000000),
            preserve_default=False,
        ),
    ]
