# Generated by Django 3.1.1 on 2020-10-26 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201013_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.country'),
            preserve_default=False,
        ),
    ]
