# Generated by Django 3.1.1 on 2020-10-31 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201026_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='picture',
        ),
    ]
