# Generated by Django 3.1.1 on 2020-12-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_major_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='account/images/country-pictures'),
        ),
    ]
