# Generated by Django 3.1.1 on 2021-01-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20201222_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='major',
            old_name='parent_major',
            new_name='parent',
        ),
    ]
