# Generated by Django 3.1.1 on 2020-10-04 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sNeeds.apps.store.basicProducts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storeBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storeBase.product')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
            ],
            bases=('storeBase.product',),
        ),
        migrations.CreateModel(
            name='HoldingDateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('picture', models.ImageField(upload_to=sNeeds.apps.store.basicProducts.models.get_lecturer_picture_path)),
                ('title', models.CharField(max_length=256)),
                ('header', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SoldBasicProduct',
            fields=[
                ('soldproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storeBase.soldproduct')),
            ],
            bases=('storeBase.soldproduct',),
        ),
        migrations.CreateModel(
            name='ClassWebinar',
            fields=[
                ('basicproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basicProducts.basicproduct')),
                ('image', models.ImageField(blank=True, null=True, upload_to=sNeeds.apps.store.basicProducts.models.get_class_webinar_image_path)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to=sNeeds.apps.store.basicProducts.models.get_class_webinar_background_image_path)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('headlines', models.TextField(blank=True, null=True)),
                ('audiences', models.TextField(blank=True, null=True)),
                ('lecturers', models.TextField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('is_held', models.BooleanField(default=False)),
                ('is_early', models.BooleanField(default=False)),
                ('early_price', models.PositiveIntegerField(blank=True, null=True)),
                ('regular_price', models.PositiveIntegerField(blank=True, null=True)),
                ('video_is_discounted', models.BooleanField(default=False)),
                ('video_regular_price', models.PositiveIntegerField(blank=True, null=True)),
                ('video_discounted_price', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('holding_date_times', models.ManyToManyField(related_name='basicproducts_classwebinar', to='basicProducts.HoldingDateTime')),
                ('lecturers_short', models.ManyToManyField(related_name='basicproducts_classwebinar', to='basicProducts.Lecturer')),
                ('question_answers', models.ManyToManyField(related_name='basicproducts_classwebinar', to='basicProducts.QuestionAnswer')),
            ],
            bases=('basicProducts.basicproduct',),
        ),
        migrations.CreateModel(
            name='SoldClassWebinar',
            fields=[
                ('soldbasicproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basicProducts.soldbasicproduct')),
            ],
            bases=('basicProducts.soldbasicproduct',),
        ),
        migrations.CreateModel(
            name='RoomLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassProduct',
            fields=[
                ('classwebinar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basicProducts.classwebinar')),
                ('type', models.CharField(default='class', max_length=10)),
            ],
            bases=('basicProducts.classwebinar',),
        ),
        migrations.CreateModel(
            name='WebinarProduct',
            fields=[
                ('classwebinar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basicProducts.classwebinar')),
                ('type', models.CharField(default='webinar', max_length=10)),
            ],
            bases=('basicProducts.classwebinar',),
        ),
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downlaodlink', to='basicProducts.classwebinar')),
            ],
        ),
        migrations.CreateModel(
            name='WebinarRoomLink',
            fields=[
                ('roomlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basicProducts.roomlink')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basicproducts_webinarroomlink', to='basicProducts.webinarproduct')),
            ],
            bases=('basicProducts.roomlink',),
        ),
        migrations.CreateModel(
            name='SoldWebinarProduct',
            fields=[
                ('soldclasswebinar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basicProducts.soldclasswebinar')),
                ('webinar_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basicProducts.webinarproduct')),
            ],
            bases=('basicProducts.soldclasswebinar',),
        ),
        migrations.CreateModel(
            name='SoldClassProduct',
            fields=[
                ('soldclasswebinar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basicProducts.soldclasswebinar')),
                ('class_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basicProducts.classproduct')),
            ],
            bases=('basicProducts.soldclasswebinar',),
        ),
        migrations.CreateModel(
            name='ClassRoomLink',
            fields=[
                ('roomlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basicProducts.roomlink')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basicproducts_classroomlink', to='basicProducts.classproduct')),
            ],
            bases=('basicProducts.roomlink',),
        ),
    ]
