# Generated by Django 3.1.1 on 2020-10-04 10:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import abroadin.apps.data.account.models
import abroadin.apps.data.account.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeModel',
            fields=[
                ('basicformfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basicformfield')),
                ('name', models.CharField(max_length=256)),
            ],
            bases=('account.basicformfield',),
        ),
        migrations.CreateModel(
            name='LanguageCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('IELTS General', 'Ielts General'), ('IELTS Academic', 'Ielts Academic'), ('TOEFL', 'Toefl'), ('GMAT', 'Gmat'), ('GRE General', 'Gre General'), ('GRE Chemistry', 'Gre Chemistry'), ('GRE Mathematics', 'Gre Mathematics'), ('GRE Literature', 'Gre Literature'), ('GRE Biology', 'Gre Biology'), ('GRE Physics', 'Gre Physics'), ('GRE Psychology', 'Gre Psychology'), ('Duolingo', 'Duolingo')], default='TOEFL', help_text='Based on endpoint just some types are allowed to insert not all certificate types.', max_length=64)),
                ('is_mock', models.BooleanField(default=False)),
                ('value', models.FloatField(editable=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetailedInfoBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume', models.FileField(blank=True, null=True, upload_to=abroadin.apps.data.account.models.get_student_resume_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), abroadin.apps.data.account.validators.validate_resume_file_size])),
                ('related_work_experience', models.PositiveIntegerField(blank=True, help_text='In months', null=True)),
                ('academic_break', models.PositiveIntegerField(blank=True, help_text='In years', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('olympiad', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFormApplySemesterYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(help_text='In Gregorian', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('semester', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], max_length=64)),
            ],
            options={
                'ordering': ['year', 'semester'],
            },
        ),
        migrations.CreateModel(
            name='DuolingoCertificate',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.languagecertificate')),
                ('overall', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(160)])),
                ('literacy', models.PositiveSmallIntegerField()),
                ('comprehension', models.PositiveSmallIntegerField()),
                ('conversation', models.PositiveSmallIntegerField()),
                ('production', models.PositiveSmallIntegerField()),
            ],
            bases=('form.languagecertificate',),
        ),
        migrations.CreateModel(
            name='GMATCertificate',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.languagecertificate')),
                ('analytical_writing_assessment', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.0)])),
                ('integrated_reasoning', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('quantitative_and_verbal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(51)])),
                ('total', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(800)])),
            ],
            bases=('form.languagecertificate',),
        ),
        migrations.CreateModel(
            name='GREGeneralCertificate',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.languagecertificate')),
                ('quantitative', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('verbal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('analytical_writing', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
            ],
            bases=('form.languagecertificate',),
        ),
        migrations.CreateModel(
            name='GRESubjectCertificate',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.languagecertificate')),
                ('quantitative', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('verbal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('analytical_writing', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('total', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(990), abroadin.apps.data.account.validators.ten_factor_validator])),
            ],
            bases=('form.languagecertificate',),
        ),
        migrations.CreateModel(
            name='RegularLanguageCertificate',
            fields=[
                ('languagecertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.languagecertificate')),
                ('speaking', models.DecimalField(decimal_places=2, max_digits=5)),
                ('listening', models.DecimalField(decimal_places=2, max_digits=5)),
                ('writing', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reading', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overall', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('form.languagecertificate',),
        ),
        migrations.CreateModel(
            name='StudentDetailedInfo',
            fields=[
                ('studentdetailedinfobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.studentdetailedinfobase')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=128, null=True)),
                ('military_service_status', models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Undid', 'Undid')], default='Undid', max_length=128, null=True)),
                ('is_married', models.BooleanField(blank=True, default=None, null=True)),
                ('payment_affordability', models.CharField(blank=True, choices=[('Low', 'Low'), ('Average', 'Average'), ('High', 'High')], default='Average', max_length=30, null=True)),
                ('prefers_full_fund', models.BooleanField(blank=True, default=None, null=True)),
                ('prefers_half_fund', models.BooleanField(blank=True, default=None, null=True)),
                ('prefers_self_fund', models.BooleanField(blank=True, default=None, null=True)),
                ('comment', models.TextField(blank=True, max_length=1024, null=True)),
                ('powerful_recommendation', models.BooleanField(blank=True, default=False, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('value', models.FloatField(editable=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('rank', models.IntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=('form.studentdetailedinfobase',),
        ),
        migrations.CreateModel(
            name='UniversityThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PH.D', 'Phd'), ('Post Doc', 'Post Doc')], default='Bachelor', max_length=128)),
                ('graduate_in', models.SmallIntegerField(help_text='In Gregorian', validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2100)])),
                ('thesis_title', models.CharField(blank=True, max_length=512, null=True)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('value', models.FloatField(editable=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.major')),
                ('student_detailed_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.studentdetailedinfobase')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.university')),
            ],
            options={
                'unique_together': {('student_detailed_info', 'grade')},
            },
        ),
        migrations.AddField(
            model_name='studentdetailedinfobase',
            name='universities',
            field=models.ManyToManyField(through='form.UniversityThrough', to='account.University'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('publish_year', models.SmallIntegerField(help_text='In Gregorian', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('which_author', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth or more', 'Fourth Or More')], default='Fourth or more', max_length=128)),
                ('type', models.CharField(choices=[('Journal', 'Journal'), ('Conference', 'Conference')], default='Journal', max_length=20)),
                ('journal_reputation', models.CharField(choices=[('One to three', 'One To Three'), ('Four to ten', 'Four To Ten'), ('Above ten', 'Above Ten')], max_length=128)),
                ('value', models.FloatField(editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('student_detailed_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.studentdetailedinfobase')),
            ],
        ),
        migrations.AddField(
            model_name='languagecertificate',
            name='student_detailed_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.studentdetailedinfobase'),
        ),
        migrations.CreateModel(
            name='GREBiologyCertificate',
            fields=[
                ('gresubjectcertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.gresubjectcertificate')),
                ('cellular_and_molecular', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('organismal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('ecology_and_evolution', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
            ],
            bases=('form.gresubjectcertificate',),
        ),
        migrations.CreateModel(
            name='GREPhysicsCertificate',
            fields=[
                ('gresubjectcertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.gresubjectcertificate')),
                ('classical_mechanics', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('electromagnetism', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('quantum_mechanics', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
            ],
            bases=('form.gresubjectcertificate',),
        ),
        migrations.CreateModel(
            name='GREPsychologyCertificate',
            fields=[
                ('gresubjectcertificate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.gresubjectcertificate')),
                ('biological', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('cognitive', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('social', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('developmental', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('clinical', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
                ('measurement_or_methodology', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(99)])),
            ],
            bases=('form.gresubjectcertificate',),
        ),
        migrations.CreateModel(
            name='WantToApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.ManyToManyField(to='account.Country')),
                ('grades', models.ManyToManyField(to='form.GradeModel')),
                ('majors', models.ManyToManyField(to='account.Major')),
                ('semester_years', models.ManyToManyField(to='form.StudentFormApplySemesterYear')),
                ('universities', models.ManyToManyField(to='account.University')),
                ('student_detailed_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='want_to_apply', to='form.studentdetailedinfo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='languagecertificate',
            unique_together={('certificate_type', 'student_detailed_info')},
        ),
    ]
