# Generated by Django 3.1.1 on 2021-04-18 13:13

import abroadin.apps.data.globaldata.models
import abroadin.apps.data.globaldata.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetailedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to=abroadin.apps.data.globaldata.models.get_student_resume_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), abroadin.apps.data.globaldata.validators.validate_resume_file_size])),
                ('related_work_experience', models.PositiveIntegerField(help_text='In months')),
                ('academic_break', models.PositiveIntegerField(help_text='In years', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('olympiad', models.CharField(blank=True, max_length=256, null=True)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=128)),
                ('is_married', models.BooleanField(blank=True, default=None, null=True)),
                ('payment_affordability', models.CharField(blank=True, choices=[('Low', 'Low'), ('Average', 'Average'), ('High', 'High')], max_length=30, null=True)),
                ('prefers_full_fund', models.BooleanField(blank=True, default=None, null=True)),
                ('prefers_half_fund', models.BooleanField(blank=True, default=None, null=True)),
                ('prefers_self_fund', models.BooleanField(blank=True, default=None, null=True)),
                ('comment', models.TextField(blank=True, max_length=1024, null=True)),
                ('powerful_recommendation', models.BooleanField()),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('rank', models.IntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='WantToApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
