# Generated by Django 3.1.1 on 2021-02-01 06:33

import abroadin.apps.data.globaldata.models
import abroadin.apps.data.globaldata.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globaldata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applydata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetailedInfoBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.UUIDField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to=abroadin.apps.data.globaldata.models.get_student_resume_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), abroadin.apps.data.globaldata.validators.validate_resume_file_size])),
                ('related_work_experience', models.PositiveIntegerField(help_text='In months')),
                ('academic_break', models.PositiveIntegerField(help_text='In years', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('olympiad', models.CharField(blank=True, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetailedInfo',
            fields=[
                ('studentdetailedinfobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.studentdetailedinfobase')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=128)),
                ('is_married', models.BooleanField(blank=True, default=None, null=True)),
                ('payment_affordability', models.CharField(blank=True, choices=[('Low', 'Low'), ('Average', 'Average'), ('High', 'High')], max_length=30, null=True)),
                ('prefers_full_fund', models.BooleanField(blank=True, default=None, null=True)),
                ('prefers_half_fund', models.BooleanField(blank=True, default=None, null=True)),
                ('prefers_self_fund', models.BooleanField(blank=True, default=None, null=True)),
                ('comment', models.TextField(blank=True, max_length=1024, null=True)),
                ('powerful_recommendation', models.BooleanField()),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('value', models.FloatField(editable=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('rank', models.IntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
            },
            bases=('form.studentdetailedinfobase',),
        ),
        migrations.CreateModel(
            name='WantToApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_detailed_info_old', models.UUIDField(blank=True, null=True)),
                ('countries', models.ManyToManyField(blank=True, to='globaldata.Country')),
                ('grades', models.ManyToManyField(blank=True, to='applydata.Grade')),
                ('majors', models.ManyToManyField(blank=True, to='globaldata.Major')),
                ('semester_years', models.ManyToManyField(blank=True, to='applydata.SemesterYear')),
                ('universities', models.ManyToManyField(blank=True, to='globaldata.University')),
                ('student_detailed_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='want_to_apply', to='form.studentdetailedinfo')),
            ],
        ),
    ]
