# Generated by Django 3.1.1 on 2021-02-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetailedinfobase',
            name='old_id',
        ),
    ]
