# Generated by Django 3.1.1 on 2021-04-18 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0001_initial'),
        ('globaldata', '0001_initial'),
        ('applydata', '0002_auto_20210418_1743'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wanttoapply',
            name='countries',
            field=models.ManyToManyField(blank=True, to='globaldata.Country'),
        ),
        migrations.AddField(
            model_name='wanttoapply',
            name='grades',
            field=models.ManyToManyField(blank=True, to='applydata.Grade'),
        ),
        migrations.AddField(
            model_name='wanttoapply',
            name='majors',
            field=models.ManyToManyField(blank=True, to='globaldata.Major'),
        ),
        migrations.AddField(
            model_name='wanttoapply',
            name='semester_years',
            field=models.ManyToManyField(blank=True, to='applydata.SemesterYear'),
        ),
        migrations.AddField(
            model_name='wanttoapply',
            name='student_detailed_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='want_to_apply', to='form.studentdetailedinfo'),
        ),
        migrations.AddField(
            model_name='wanttoapply',
            name='universities',
            field=models.ManyToManyField(blank=True, to='globaldata.University'),
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
