# Generated by Django 3.1.1 on 2021-02-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_remove_studentdetailedinfobase_old_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wanttoapply',
            name='student_detailed_info_old',
        ),
    ]
