# Generated by Django 3.1.1 on 2020-10-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20201013_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='journal_reputation',
            field=models.CharField(choices=[('One to three', 'One to three'), ('Four to ten', 'Four to ten'), ('Above ten', 'Above ten')], max_length=128),
        ),
        migrations.AlterField(
            model_name='publication',
            name='which_author',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth or more', 'Fourth or more')], default='Fourth or more', max_length=128),
        ),
        migrations.AlterField(
            model_name='universitythrough',
            name='grade',
            field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PH.D', 'PH.D'), ('Post Doc', 'Post Doc')], default='Bachelor', max_length=128),
        ),
    ]
