# Generated by Django 3.1.1 on 2020-10-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20201013_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wanttoapply',
            name='grades',
        ),
        migrations.AddField(
            model_name='wanttoapply',
            name='grades',
            field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PH.D', 'PH.D'), ('Post Doc', 'Post Doc')], default='Bachelor', max_length=128),
        ),
        migrations.DeleteModel(
            name='GradeModel',
        ),
    ]
