# Generated by Django 3.1.1 on 2021-02-19 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_remove_wanttoapply_student_detailed_info_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
