# Generated by Django 3.1.1 on 2021-02-23 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20210219_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
