# Generated by Django 3.1.1 on 2020-10-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20201013_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetailedinfo',
            name='military_service_status',
        ),
    ]
