# Generated by Django 3.1.1 on 2021-04-18 07:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0005_auto_20210223_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetailedinfobase',
            name='t_age',
            field=models.PositiveSmallIntegerField(default=66, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetailedinfobase',
            name='t_comment',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='studentdetailedinfobase',
            name='t_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetailedinfobase',
            name='t_homepage_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdetailedinfobase',
            name='t_is_married',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentdetailedinfobase',
            name='t_linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdetailedinfobase',
            name='t_payment_affordability',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Average', 'Average'), ('High', 'High')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentdetailedinfobase',
            name='t_powerful_recommendation',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetailedinfobase',
            name='t_prefers_full_fund',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentdetailedinfobase',
            name='t_prefers_half_fund',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentdetailedinfobase',
            name='t_prefers_self_fund',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentdetailedinfobase',
            name='t_rank',
            field=models.IntegerField(default=44, editable=False, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetailedinfobase',
            name='t_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, default=2785),
        ),
        migrations.AddField(
            model_name='studentdetailedinfobase',
            name='t_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),

    ]
