# Generated by Django 3.1.1 on 2020-10-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_remove_studentdetailedinfo_military_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=128, null=True),
        ),
    ]
