# Generated by Django 3.1.1 on 2020-10-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20201022_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='payment_affordability',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Average', 'Average'), ('High', 'High')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='powerful_recommendation',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
