# Generated by Django 3.1.1 on 2020-10-22 17:10

from django.db import migrations, models

from abroadin.apps.data.applydata.models import GradeChoices


def add_grades(apps, schema_editor):
    '''
    Initializing Grade model data because data is fixed.
    '''
    Grade = apps.get_model('form', 'Grade')
    for member in GradeChoices:
        Grade.objects.get_or_create(name=member)


def delete_grades(apps, schema_editor):
    '''
    Deletes Grade model data because for reverse migrations.
    '''
    Grade = apps.get_model('form', 'Grade')
    Grade.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('form', '0007_auto_20201022_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PH.D', 'PH.D'),
                                                   ('Post Doc', 'Post Doc')], default='Bachelor', max_length=128,
                                          unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='wanttoapply',
            name='grades',
        ),
        migrations.AddField(
            model_name='wanttoapply',
            name='grades',
            field=models.ManyToManyField(to='form.Grade'),
        ),
        migrations.RunPython(add_grades, delete_grades),
    ]
