# Generated by Django 3.1.1 on 2020-10-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('similarApply', '0003_auto_20201013_1839'),
        ('form', '0008_auto_20201022_2040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentFormApplySemesterYear',
            new_name='SemesterYear',
        ),
    ]
