# Generated by Django 3.1.1 on 2020-10-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_auto_20201023_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagecertificate',
            name='value',
        ),
    ]
