# Generated by Django 3.1.1 on 2021-04-18 13:03

import abroadin.apps.data.globaldata.models
import abroadin.apps.data.globaldata.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0009_auto_20210418_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetailedinfo',
            name='studentdetailedinfobase_ptr',
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='academic_break',
            field=models.PositiveIntegerField(default=11111, help_text='In years', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='age',
            field=models.PositiveSmallIntegerField(default=1111, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='comment',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=11111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=111111, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='homepage_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=11111, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='is_married',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='olympiad',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='payment_affordability',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Average', 'Average'), ('High', 'High')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='powerful_recommendation',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='prefers_full_fund',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='prefers_half_fund',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='prefers_self_fund',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='rank',
            field=models.IntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='related_work_experience',
            field=models.PositiveIntegerField(default=1, help_text='In months'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=abroadin.apps.data.globaldata.models.get_student_resume_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), abroadin.apps.data.globaldata.validators.validate_resume_file_size]),
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='customAuth.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='StudentDetailedInfoBase',
        ),
    ]
