# Generated by Django 3.1.1 on 2020-11-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_remove_languagecertificate_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularlanguagecertificate',
            name='listening',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='regularlanguagecertificate',
            name='overall',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='regularlanguagecertificate',
            name='reading',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='regularlanguagecertificate',
            name='speaking',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='regularlanguagecertificate',
            name='writing',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
