# Generated by Django 3.1.1 on 2020-11-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_auto_20201102_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularlanguagecertificate',
            name='listening',
            field=models.DecimalField(decimal_places=1, help_text=' IELTS listening 0 to 9 and TOEFL listening 0 to 30', max_digits=4),
        ),
        migrations.AlterField(
            model_name='regularlanguagecertificate',
            name='overall',
            field=models.DecimalField(decimal_places=1, help_text=' IELTS overall 1 to 9 and TOEFL overall 0 to 120', max_digits=4),
        ),
        migrations.AlterField(
            model_name='regularlanguagecertificate',
            name='reading',
            field=models.DecimalField(decimal_places=1, help_text=' IELTS reading 0 to 9 and TOEFL reading 0 to 30', max_digits=4),
        ),
        migrations.AlterField(
            model_name='regularlanguagecertificate',
            name='speaking',
            field=models.DecimalField(decimal_places=1, help_text=' IELTS speaking 0 to 9 and TOEFL speaking 0 to 30', max_digits=4),
        ),
        migrations.AlterField(
            model_name='regularlanguagecertificate',
            name='writing',
            field=models.DecimalField(decimal_places=1, help_text=' IELTS writing 0 to 9 and TOEFL writing 0 to 30', max_digits=4),
        ),
    ]
