# Generated by Django 3.1.1 on 2020-12-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_major_picture'),
        ('form', '0012_auto_20201121_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanttoapply',
            name='countries',
            field=models.ManyToManyField(blank=True, to='account.Country'),
        ),
        migrations.AlterField(
            model_name='wanttoapply',
            name='grades',
            field=models.ManyToManyField(blank=True, to='form.Grade'),
        ),
        migrations.AlterField(
            model_name='wanttoapply',
            name='majors',
            field=models.ManyToManyField(blank=True, to='account.Major'),
        ),
        migrations.AlterField(
            model_name='wanttoapply',
            name='semester_years',
            field=models.ManyToManyField(blank=True, to='form.SemesterYear'),
        ),
        migrations.AlterField(
            model_name='wanttoapply',
            name='universities',
            field=models.ManyToManyField(blank=True, to='account.University'),
        ),
    ]
