# Generated by Django 3.1.1 on 2020-12-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_auto_20201216_1243'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentdetailedinfo',
            index=models.Index(fields=['rank'], name='form_studen_rank_cf4522_idx'),
        ),
    ]
