# Generated by Django 3.1.1 on 2020-12-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0014_auto_20201221_1359'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentdetailedinfo',
            name='form_studen_rank_cf4522_idx',
        ),
        migrations.AddIndex(
            model_name='studentdetailedinfo',
            index=models.Index(fields=['value'], name='form_studen_value_ce7fc6_idx'),
        ),
    ]
