# Generated by Django 3.1.1 on 2020-12-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0016_auto_20201221_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdetailedinfo',
            options={'ordering': ['rank']},
        ),
        migrations.RemoveIndex(
            model_name='studentdetailedinfo',
            name='form_studen_value_06b3cd_idx',
        ),
    ]
