# Generated by Hossein Mohammadi on 2021-01-01


##    ##      ##      ####   ####   ##   ##    ░█████╗░██╗░░██╗██████╗░██╗░██████╗████████╗███╗░░░███╗░█████╗░░██████╗
##    ##     ####     ## ##  ## ##   ## ##     ██╔══██╗██║░░██║██╔══██╗██║██╔════╝╚══██╔══╝████╗░████║██╔══██╗██╔════╝
########    ## # #    ####   ####     ###      ██║░░╚═╝███████║██████╔╝██║╚█████╗░░░░██║░░░██╔████╔██║███████║╚█████╗░
##    ##   ##    ##   ##     ##        #       ██║░░██╗██╔══██║██╔══██╗██║░╚═══██╗░░░██║░░░██║╚██╔╝██║██╔══██║░╚═══██╗
##    ##  ##      ##  ##     ##        #       ╚█████╔╝██║░░██║██║░░██║██║██████╔╝░░░██║░░░██║░╚═╝░██║██║░░██║██████╔╝


from django.db import migrations


def semester_year_forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    FormSemesterYear = apps.get_model("form", "semesteryear")
    ApplyDataSemesterYear = apps.get_model("applydata", "semesteryear")
    for obj in FormSemesterYear.objects.all():
        ApplyDataSemesterYear.objects.create(
            year=obj.year,
            semester=obj.semester,
        )


def grade_forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    FormGrade = apps.get_model("form", "grade")
    ApplyDataGrade = apps.get_model("applydata", "grade")
    for obj in FormGrade.objects.all():
        ApplyDataGrade.objects.create(
            name=obj.name,
        )


def publication_forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    FormPublication = apps.get_model("form", "publication")
    ApplyDataPublication = apps.get_model("applydata", "publication")
    for obj in FormPublication.objects.all():
        ApplyDataPublication.objects.create(
            content_object=obj.student_detailed_info,
            title=obj.title,
            publish_year=obj.publish_year,
            which_author=obj.which_author,
            type=obj.type,
            journal_reputation=obj.journal_reputation,
            value=obj.value,
        )


def education_forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    FormUniversityThrough = apps.get_model("form", "universitythrough")
    ApplyDataEducation = apps.get_model("applydata", "education")
    for obj in FormUniversityThrough.objects.all():
        ApplyDataEducation.objects.create(
            content_object=obj.student_detailed_info,
            university=obj.university,
            grade=obj.grade,
            major=obj.major,
            graduate_in=obj.graduate_in,
            thesis_title=obj.thesis_title,
            gpa=obj.gpa,
            value=obj.value,
        )


def regular_lc_forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    FormRegularLanguageCertificate = apps.get_model("form", "regularlanguagecertificate")
    ApplyDataRegularLanguageCertificate = apps.get_model("applydata", "regularlanguagecertificate")
    for obj in FormRegularLanguageCertificate.objects.all():
        ApplyDataRegularLanguageCertificate.objects.create(
            content_object=obj.student_detailed_info,
            certificate_type=obj.certificate_type,
            is_mock=obj.is_mock,
            speaking=obj.speaking,
            listening=obj.listening,
            writing=obj.writing,
            reading=obj.reading,
            overall=obj.overall,
        )


def gmat_lc_forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    FormGMATCertificate = apps.get_model("form", "gmatcertificate")
    ApplyDataGMATCertificate = apps.get_model("applydata", "gmatcertificate")
    for obj in FormGMATCertificate.objects.all():
        ApplyDataGMATCertificate.objects.create(
            content_object=obj.student_detailed_info,
            certificate_type=obj.certificate_type,
            is_mock=obj.is_mock,
            analytical_writing_assessment=obj.analytical_writing_assessment,
            integrated_reasoning=obj.integrated_reasoning,
            quantitative_and_verbal=obj.quantitative_and_verbal,
            total=obj.total,
        )


def gre_general_lc_forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    FormGREGeneralCertificate = apps.get_model("form", "gregeneralcertificate")
    ApplyDataGREGeneralCertificate = apps.get_model("applydata", "gregeneralcertificate")
    for obj in FormGREGeneralCertificate.objects.all():
        ApplyDataGREGeneralCertificate.objects.create(
            content_object=obj.student_detailed_info,
            certificate_type=obj.certificate_type,
            is_mock=obj.is_mock,
            quantitative=obj.quantitative,
            verbal=obj.verbal,
            analytical_writing=obj.analytical_writing,
        )


def gre_subject_lc_forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    FormGRESubjectCertificate = apps.get_model("form", "gresubjectcertificate")
    ApplyDataGRESubjectCertificate = apps.get_model("applydata", "gresubjectcertificate")
    for obj in FormGRESubjectCertificate.objects.filter(certificate_type__in=['GRE Chemistry', 'GRE Mathematics',
                                                                              'GRE Literature']):
        ApplyDataGRESubjectCertificate.objects.create(
            content_object=obj.student_detailed_info,
            certificate_type=obj.certificate_type,
            is_mock=obj.is_mock,
            quantitative=obj.quantitative,
            verbal=obj.verbal,
            analytical_writing=obj.analytical_writing,
            total=obj.total,
        )


def gre_biology_lc_forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    FormGREBiologyCertificate = apps.get_model("form", "grebiologycertificate")
    ApplyDataGREBiologyCertificate = apps.get_model("applydata", "grebiologycertificate")
    for obj in FormGREBiologyCertificate.objects.all():
        ApplyDataGREBiologyCertificate.objects.create(
            content_object=obj.student_detailed_info,
            certificate_type=obj.certificate_type,
            is_mock=obj.is_mock,
            quantitative=obj.quantitative,
            verbal=obj.verbal,
            analytical_writing=obj.analytical_writing,
            total=obj.total,
            cellular_and_molecular=obj.cellular_and_molecular,
            organismal=obj.organismal,
            ecology_and_evolution=obj.ecology_and_evolution,
        )


def gre_physics_lc_forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    FormGREPhysicsCertificate = apps.get_model("form", "grephysicscertificate")
    ApplyDataGREPhysicsCertificate = apps.get_model("applydata", "grephysicscertificate")
    for obj in FormGREPhysicsCertificate.objects.all():
        ApplyDataGREPhysicsCertificate.objects.create(
            content_object=obj.student_detailed_info,
            certificate_type=obj.certificate_type,
            is_mock=obj.is_mock,
            quantitative=obj.quantitative,
            verbal=obj.verbal,
            analytical_writing=obj.analytical_writing,
            total=obj.total,
            classical_mechanics=obj.classical_mechanics,
            electromagnetism=obj.electromagnetism,
            quantum_mechanics=obj.quantum_mechanics,
        )


def gre_psychology_lc_forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    FormGREPsychologyCertificate = apps.get_model("form", "grepsychologcertificate")
    ApplyDataGREPsychologyCertificate = apps.get_model("applydata", "grepsychologcertificate")
    for obj in FormGREPsychologyCertificate.objects.all():
        ApplyDataGREPsychologyCertificate.objects.create(
            content_object=obj.student_detailed_info,
            certificate_type=obj.certificate_type,
            is_mock=obj.is_mock,
            quantitative=obj.quantitative,
            verbal=obj.verbal,
            analytical_writing=obj.analytical_writing,
            total=obj.total,
            biological=obj.biological,
            cognitive=obj.cognitive,
            social=obj.social,
            developmental=obj.developmental,
            clinical=obj.clinical,
            measurement_or_methodology=obj.measurement_or_methodology,
        )


def duolingo_lc_forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    FormDuolingoCertificate = apps.get_model("form", "duolingocertificate")
    ApplyDataDuolingoCertificate = apps.get_model("applydata", "duolingocertificate")
    for obj in FormDuolingoCertificate.objects.all():
        ApplyDataDuolingoCertificate.objects.create(
            content_object=obj.student_detailed_info,
            certificate_type=obj.certificate_type,
            is_mock=obj.is_mock,
            overall=obj.overall,
            literacy=obj.literacy,
            comprehension=obj.comprehension,
            conversation=obj.conversation,
            production=obj.production,
        )


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Form = apps.get_model("form", "")
    ApplyData = apps.get_model("applydata", "")
    for obj in Form.objects.all():
        ApplyData.objects.create(
            content_object=obj.student_detailed_info,
            certificate_type=obj.certificate_type,
            is_mock=obj.is_mock,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('form', '0017_auto_20201222_1050'),
        ('account', '0009_auto_20201222_1050'),
        ('applydata',
         '0002_duolingocertificate_gmatcertificate_grebiologycertificate_gregeneralcertificate_grephysicscertificat')
    ]

    operations = [
        migrations.RunPython(
            code=semester_year_forwards_func,
        ),
        migrations.RunPython(
            code=grade_forwards_func
        ),
        migrations.RunPython(
            code=publication_forwards_func
        ),
        migrations.RunPython(
            code=education_forwards_func
        ),
        migrations.RunPython(
            code=regular_lc_forwards_func
        ),
        migrations.RunPython(
            code=gmat_lc_forwards_func
        ),
        migrations.RunPython(
            code=gre_general_lc_forwards_func
        ),
        migrations.RunPython(
            code=gre_subject_lc_forwards_func
        ),
        migrations.RunPython(
            code=gre_biology_lc_forwards_func
        ),
        migrations.RunPython(
            code=gre_physics_lc_forwards_func
        ),
        migrations.RunPython(
            code=gre_psychology_lc_forwards_func
        ),
        migrations.RunPython(
            code=duolingo_lc_forwards_func
        ),
    ]
