# Generated by Hossein Mohammadi on 2021-01-01


# ##    ##      ##      ####   ####   ##   ##    ░█████╗░██╗░░██╗██████╗░██╗░██████╗████████╗███╗░░░███╗░█████╗░░██████╗
# ##    ##     ####     ## ##  ## ##   ## ##     ██╔══██╗██║░░██║██╔══██╗██║██╔════╝╚══██╔══╝████╗░████║██╔══██╗██╔════╝
# ########    ## # #    ####   ####     ###      ██║░░╚═╝███████║██████╔╝██║╚█████╗░░░░██║░░░██╔████╔██║███████║╚█████╗░
# ##    ##   ##    ##   ##     ##        #       ██║░░██╗██╔══██║██╔══██╗██║░╚═══██╗░░░██║░░░██║╚██╔╝██║██╔══██║░╚═══██╗
# ##    ##  ##      ##  ##     ##        #       ╚█████╔╝██║░░██║██║░░██║██║██████╔╝░░░██║░░░██║░╚═╝░██║██║░░██║██████╔╝


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0018_copy_form_objects_to_apply_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantToApplyTransferSemesterGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('want_to_apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.wanttoapply')),
                ('form_grades', models.ManyToManyField(to='form.Grade')),
                ('form_semester_years', models.ManyToManyField(to='form.SemesterYear')),
                ('apply_data_grades', models.ManyToManyField(to='applydata.Grade')),
                ('apply_data_semester_years', models.ManyToManyField(to='applydata.SemesterYear')),
            ],
        ),
    ]
