# Generated by Hossein Mohammadi on 2021-01-01


#            █████
#         █████████
#         ████████
#           ███████
#           ████████
#       ██████████████
#      ███▒▒░░░░░░░░▒
#        ▒░░░░░ ⓤ░░ⓤ░▒
#        ▒░░░░░░░░ >░░ ▒
#        ██▒░░░░░·︾·░░▒
#        ████▒░░░░░░░▒
#       ▒▒███████████▒▒
#     ▒░░░░░▒▒▒▒███░░░▒
#    ▒░░░▒░░░░░░████░░ ▒
#    ▒░░░░▒░░░░░█████░░▒
#    ▒░░░░░▒░░░░███████░▒
#     ▒░░░░▒░░░░██████▒▒
#     ▒#▒▒▒▒▒░##░██████
#   ▒#▒░░░░░░░░░░░░░▒░▒
#  ▒░░░░░░░░░░░░░░Ѻ░░░▒
# ▒░░░░░░░░░░░░░░░░░░░ ▒
# ▒░░░░░░░░░░░░░░░Ѻ░░░ ▒
# ▒░░░░░░░░░░░░░░░░░░░ ▒
#  ▒░░░░░░░░░░░░░Ѻ░░░░▒
#  ▒░░░░░░░░░░░░░░░░░░▒

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    # FormWantToApplyTransferSemesterGrade = apps.get_model("form", "wanttoapplytransfersemestergrade")
    # for obj in FormWantToApplyTransferSemesterGrade.objects.all():
    #     obj.want_to_apply.semester_years.set(list(obj.apply_data_semester_years.all()))
    #     obj.want_to_apply.grades.set(obj.apply_data_grades.all())
    pass


def reverse_func(apps, schema_editor):
    # pass
    FormWantToApplyTransferSemesterGrade = apps.get_model("form", "wanttoapplytransfersemestergrade")
    for obj in FormWantToApplyTransferSemesterGrade.objects.all():
        if obj.form_semester_years.all().exists():
            obj.want_to_apply.semester_years.set(list(obj.form_semester_years.all()))
        if obj.form_grades.all().exists():
            obj.want_to_apply.grades.set(list(obj.form_grades.all()))


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0020_store_wanttoapply_grade_and_semester_in_middle_model'),
    ]

    operations = [
        migrations.RunPython(
            code=forwards_func, reverse_code=reverse_func,
        )
    ]