# Generated by Hossein Mohammadi on 2021-01-01


# ##    ##      ##      ####   ####   ##   ##    ░█████╗░██╗░░██╗██████╗░██╗░██████╗████████╗███╗░░░███╗░█████╗░░██████╗
# ##    ##     ####     ## ##  ## ##   ## ##     ██╔══██╗██║░░██║██╔══██╗██║██╔════╝╚══██╔══╝████╗░████║██╔══██╗██╔════╝
# ########    ## # #    ####   ####     ###      ██║░░╚═╝███████║██████╔╝██║╚█████╗░░░░██║░░░██╔████╔██║███████║╚█████╗░
# ##    ##   ##    ##   ##     ##        #       ██║░░██╗██╔══██║██╔══██╗██║░╚═══██╗░░░██║░░░██║╚██╔╝██║██╔══██║░╚═══██╗
# ##    ##  ##      ##  ##     ##        #       ╚█████╔╝██║░░██║██║░░██║██║██████╔╝░░░██║░░░██║░╚═╝░██║██║░░██║██████╔╝

from django.db import migrations

CACHED_APPLYDATA_SEMESTER_YEARS = {

}


def _get_new_semester_years(apps, schema_editor, old_ones: iter):
    ApplyDataSemesterYear = apps.get_model("applydata", "semesteryear")
    new_ones = []
    for old_one in old_ones:
        identifier = str(old_one.year) + '_||_' + old_one.semester
        if identifier not in CACHED_APPLYDATA_SEMESTER_YEARS:
            obj = ApplyDataSemesterYear.objects.get(semester=old_one.semester, year=old_one.year)
            CACHED_APPLYDATA_SEMESTER_YEARS[identifier] = obj
        new_ones.append(CACHED_APPLYDATA_SEMESTER_YEARS[identifier])
    return new_ones


CACHED_APPLYDATA_GRADES = {

}


def _get_new_grades(apps, schema_editor, old_ones: iter):
    ApplyDataGrade = apps.get_model("applydata", "grade")
    new_ones = []
    for old_one in old_ones:
        identifier = str(old_one.name) + '_||_'
        if identifier not in CACHED_APPLYDATA_GRADES:
            obj = ApplyDataGrade.objects.get(name=old_one.name)
            CACHED_APPLYDATA_GRADES[identifier] = obj
        new_ones.append(CACHED_APPLYDATA_GRADES[identifier])
    return new_ones


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    FormWantToApplyTransferSemesterGrade = apps.get_model("form", "wanttoapplytransfersemestergrade")
    for obj in FormWantToApplyTransferSemesterGrade.objects.all():
        obj.want_to_apply.semester_years.set([obj.form_semester_years])
        obj.want_to_apply.grades.set([obj.form_grades])


def _forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Form = apps.get_model("form", "")
    Form.objects.all().delete()


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Form = apps.get_model("form", "")
    ApplyData = apps.get_model("applydata", "")
    for obj in ApplyData.objects.all():
        Form.objects.create(
            student_detailed_info=obj.content_object,
            certificate_type=obj.certificate_type,
            is_mock=obj.is_mock,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('form', '0021_alter_wanttoapply_grade_semester_to_use_new_fields'),
    ]

    operations = [
        migrations.RunPython(
            code=forwards_func,
        ),
    ]
