# Generated by Hossein Mohammadi on 2021-01-01


#            █████
#         █████████
#         ████████
#           ███████
#           ████████
#       ██████████████
#      ███▒▒░░░░░░░░▒
#        ▒░░░░░ ⓤ░░ⓤ░▒
#        ▒░░░░░░░░ >░░ ▒
#        ██▒░░░░░·︾·░░▒
#        ████▒░░░░░░░▒
#       ▒▒███████████▒▒
#     ▒░░░░░▒▒▒▒███░░░▒
#    ▒░░░▒░░░░░░████░░ ▒
#    ▒░░░░▒░░░░░█████░░▒
#    ▒░░░░░▒░░░░███████░▒
#     ▒░░░░▒░░░░██████▒▒
#     ▒#▒▒▒▒▒░##░██████
#   ▒#▒░░░░░░░░░░░░░▒░▒
#  ▒░░░░░░░░░░░░░░Ѻ░░░▒
# ▒░░░░░░░░░░░░░░░░░░░ ▒
# ▒░░░░░░░░░░░░░░░Ѻ░░░ ▒
# ▒░░░░░░░░░░░░░░░░░░░ ▒
#  ▒░░░░░░░░░░░░░Ѻ░░░░▒
#  ▒░░░░░░░░░░░░░░░░░░▒

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0021_only_unapply__wanttoapply_grade_semester_set_value_from_from_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wanttoapply',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='wanttoapply',
            name='semester_years',
        ),
    ]