# Generated by Hossein Mohammadi on 2021-01-01


#            █████
#         █████████
#         ████████
#           ███████
#           ████████
#       ██████████████
#      ███▒▒░░░░░░░░▒
#        ▒░░░░░ ⓤ░░ⓤ░▒
#        ▒░░░░░░░░ >░░ ▒
#        ██▒░░░░░·︾·░░▒
#        ████▒░░░░░░░▒
#       ▒▒███████████▒▒
#     ▒░░░░░▒▒▒▒███░░░▒
#    ▒░░░▒░░░░░░████░░ ▒
#    ▒░░░░▒░░░░░█████░░▒
#    ▒░░░░░▒░░░░███████░▒
#     ▒░░░░▒░░░░██████▒▒
#     ▒#▒▒▒▒▒░##░██████
#   ▒#▒░░░░░░░░░░░░░▒░▒
#  ▒░░░░░░░░░░░░░░Ѻ░░░▒
# ▒░░░░░░░░░░░░░░░░░░░ ▒
# ▒░░░░░░░░░░░░░░░Ѻ░░░ ▒
# ▒░░░░░░░░░░░░░░░░░░░ ▒
#  ▒░░░░░░░░░░░░░Ѻ░░░░▒
#  ▒░░░░░░░░░░░░░░░░░░▒

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0022_wanttoapply_remove_grade_semester_related_to_form_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanttoapply',
            name='grades',
            field=models.ManyToManyField(to='applydata.Grade'),
        ),
        migrations.AddField(
            model_name='wanttoapply',
            name='semester_years',
            field=models.ManyToManyField(to='applydata.SemesterYear'),
        ),
    ]