# Generated by Hossein Mohammadi on 2021-01-01


#            █████
#         █████████
#         ████████
#           ███████
#           ████████
#       ██████████████
#      ███▒▒░░░░░░░░▒
#        ▒░░░░░ ⓤ░░ⓤ░▒
#        ▒░░░░░░░░ >░░ ▒
#        ██▒░░░░░·︾·░░▒
#        ████▒░░░░░░░▒
#       ▒▒███████████▒▒
#     ▒░░░░░▒▒▒▒███░░░▒
#    ▒░░░▒░░░░░░████░░ ▒
#    ▒░░░░▒░░░░░█████░░▒
#    ▒░░░░░▒░░░░███████░▒
#     ▒░░░░▒░░░░██████▒▒
#     ▒#▒▒▒▒▒░##░██████
#   ▒#▒░░░░░░░░░░░░░▒░▒
#  ▒░░░░░░░░░░░░░░Ѻ░░░▒
# ▒░░░░░░░░░░░░░░░░░░░ ▒
# ▒░░░░░░░░░░░░░░░Ѻ░░░ ▒
# ▒░░░░░░░░░░░░░░░░░░░ ▒
#  ▒░░░░░░░░░░░░░Ѻ░░░░▒
#  ▒░░░░░░░░░░░░░░░░░░▒

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    FormWantToApplyTransferSemesterGrade = apps.get_model("form", "wanttoapplytransfersemestergrade")
    for obj in FormWantToApplyTransferSemesterGrade.objects.all():
        obj.want_to_apply.semester_years.set([sy for sy in obj.apply_data_semester_years.all()])
        obj.want_to_apply.grades.set([grade for grade in obj.apply_data_grades.all()])


def reverse_func(apps, schema_editor):
    pass
    # FormWantToApplyTransferSemesterGrade = apps.get_model("form", "wanttoapplytransfersemestergrade")
    # for obj in FormWantToApplyTransferSemesterGrade.objects.all():
    #     if obj.form_semester_years.all().exists():
    #         obj.want_to_apply.semester_years.set(list(obj.form_semester_years.all()))
    #     if obj.form_grades.all().exists():
    #         obj.want_to_apply.grades.set(list(obj.form_grades.all()))


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0023_wanttoapply_add_grade_semester_related_to_apply_data_models'),
    ]

    operations = [
        migrations.RunPython(
            code=forwards_func, reverse_code=reverse_func,
        )
    ]