# Generated by Hossein Mohammadi on 2021-01-01

#                  11111
#            ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶11
#          ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
#         ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1
#        ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
#       ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1
#      ¶¶¶¶¶¶¶¶¶11111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
#    ¶¶¶¶1                   ¶¶¶¶¶¶¶¶¶¶¶¶¶¶
#  ¶¶¶                          1¶¶¶¶¶¶¶¶¶¶¶
#  ¶1                              1¶¶¶¶¶¶¶¶¶
# 1¶          111                     ¶¶¶¶¶¶¶¶
# 1¶      ¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1           ¶¶¶¶¶¶¶¶
#  ¶   ¶¶¶¶1             1¶¶¶¶¶1      1¶¶¶¶¶¶¶
#  ¶1 ¶¶¶¶  1¶¶¶¶¶¶     11111¶¶¶¶     ¶¶¶¶¶¶¶¶
#   ¶¶¶¶¶11¶¶¶¶¶¶¶¶¶   ¶¶¶¶¶¶¶¶1¶¶¶1  ¶¶¶¶¶¶¶¶
#    ¶¶¶¶    1¶¶¶¶¶1   ¶¶1¶¶¶    ¶¶¶¶¶¶¶¶¶¶¶¶¶
#    ¶11¶      ¶1¶¶     ¶1¶1     ¶¶¶¶¶¶¶¶¶¶¶¶¶
#    ¶  ¶1       ¶1     ¶1       ¶¶¶1 ¶¶¶¶¶¶¶1
#    ¶  ¶¶1   11¶¶¶1   ¶¶¶1      ¶¶¶¶  ¶¶¶¶¶¶
#    ¶   ¶¶¶¶¶¶111¶¶¶¶¶¶1 ¶¶¶¶¶¶¶¶ ¶¶  ¶¶¶¶¶¶
#   1¶    ¶¶         1        1¶1   ¶   ¶¶¶¶1
#   1¶      1    1¶¶¶¶¶¶¶1          ¶1  ¶¶¶¶¶
#   1¶       ¶¶¶¶¶¶     ¶¶¶¶¶¶      ¶1 ¶¶   ¶¶
#    ¶              111             ¶1¶¶     1¶
#    ¶1                             ¶1¶       ¶
#    ¶¶                            ¶¶ ¶¶      ¶
#     ¶1                           ¶   ¶¶¶11¶¶
#      ¶1                         ¶¶     11
#       ¶¶                       ¶¶
#        ¶¶                     ¶¶
#         1¶¶                 1¶
#           ¶¶1             1¶¶
#             ¶¶¶        1¶¶¶
#               1¶¶111¶¶¶1


from django.db import migrations


CACHED_APPLYDATA_SEMESTER_YEARS = {}


def _get_apply_data_semester_years(apps, schema_editor, form_ones: iter):
    ApplyDataSemesterYear = apps.get_model("applydata", "semesteryear")
    applydata_ones = []
    for old_one in form_ones:
        identifier = str(old_one.year) + '_||_' + old_one.semester
        if identifier not in CACHED_APPLYDATA_SEMESTER_YEARS:
            obj = ApplyDataSemesterYear.objects.filter(semester=old_one.semester, year=old_one.year).first()
            CACHED_APPLYDATA_SEMESTER_YEARS[identifier] = obj
        applydata_ones.append(CACHED_APPLYDATA_SEMESTER_YEARS[identifier])
    return applydata_ones


CACHED_APPLYDATA_GRADES = {}


def _get_apply_data_grades(apps, schema_editor, form_ones: iter):
    ApplyDataGrade = apps.get_model("applydata", "grade")
    applydata_ones = []
    for old_one in form_ones:
        identifier = str(old_one.name) + '_||_'
        if identifier not in CACHED_APPLYDATA_GRADES:
            obj = ApplyDataGrade.objects.get(name=old_one.name)
            CACHED_APPLYDATA_GRADES[identifier] = obj
        applydata_ones.append(CACHED_APPLYDATA_GRADES[identifier])
    return applydata_ones


def forward_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    FormWantToApplyTransferSemesterGrade = apps.get_model("form", "wanttoapplytransfersemestergrade")
    FormWantToApplyTransferSemesterGrade.objects.all().delete()


def reverse_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    FormWantToApply = apps.get_model("form", "wanttoapply")
    FormWantToApplyTransferSemesterGrade = apps.get_model("form", "wanttoapplytransfersemestergrade")
    FormWantToApplyTransferSemesterGrade.objects.all().delete()
    for obj in FormWantToApply.objects.all():
        mid_obj = FormWantToApplyTransferSemesterGrade.objects.create(
            want_to_apply=obj,
        )
        mid_obj.form_semester_years.set(list(obj.semester_years.all()))
        mid_obj.form_grades.set(list(obj.grades.all()))
        mid_obj.apply_data_semester_years.set(_get_apply_data_semester_years(apps, schema_editor, obj.semester_years.all()))
        mid_obj.apply_data_grades.set(_get_apply_data_grades(apps, schema_editor, obj.grades.all()))


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0024_only_apply__wanttoapply_grade_semester_set_value_from_apply_data_models'),
    ]

    operations = [
        migrations.RunPython(
            code=forward_func, reverse_code=reverse_func,
        ),
    ]