# Generated by Hossein Mohammadi on 2021-01-01

#                       ¶¶ 
#                       ¶¶ 
#                      ¶¶¶¶ 
#                      ¶  ¶ 
#                     ¶   ¶¶ 
#                    ¶¶    ¶¶ 
#                   ¶¶      ¶ 
#                  ¶¶¶¶     ¶¶ 
#                  ¶ ¶ ¶¶  ¶ ¶¶ 
#                    ¶¶¶¶¶¶¶¶¶¶ 
#                   ¶¶¶  ¶¶¶  ¶¶ 
#                 ¶¶¶     ¶¶   ¶¶ 
#                ¶¶             ¶¶ 
#               ¶¶               ¶¶ 
#             ¶¶¶               ¶¶¶¶ 
#               ¶¶¶¶¶           ¶¶ 
#                ¶¶¶ ¶¶¶ ¶¶ ¶¶¶  ¶¶ 
#              ¶¶ ¶¶¶¶ ¶¶¶¶ ¶¶¶¶¶¶¶¶ 
#            ¶¶¶  ¶¶¶   ¶¶ ¶¶¶  ¶¶ ¶¶¶ 
#             ¶         ¶¶  ¶¶       ¶¶ 
#          ¶¶¶                        ¶¶¶ 
#           ¶¶¶¶                  ¶   ¶¶¶ 
#             ¶¶                  ¶¶¶¶¶ 
#            ¶¶  ¶      ¶   ¶  ¶¶  ¶¶¶¶ 
#           ¶¶ ¶¶¶¶    ¶¶¶  ¶¶ ¶¶¶¶¶¶ ¶¶ 
#            ¶¶¶ ¶    ¶¶¶¶  ¶¶¶¶  ¶¶¶  ¶¶ 
#            ¶¶ ¶¶ ¶¶¶¶  ¶ ¶¶ ¶¶    ¶   ¶¶¶ 
#          ¶¶¶  ¶¶¶¶¶   ¶¶¶¶  ¶           ¶¶¶ 
#       ¶¶¶¶             ¶¶                 ¶¶¶ 
#      ¶¶¶¶¶¶¶                               ¶¶¶¶¶ 
#            ¶                     ¶¶  ¶¶¶¶¶¶¶ 
#           ¶¶                  ¶¶ ¶¶¶¶¶¶  ¶¶ 
#          ¶¶                   ¶¶¶¶¶  ¶¶   ¶¶ 
#        ¶¶¶  ¶¶¶     ¶  ¶  ¶¶¶ ¶¶ ¶¶¶       ¶¶ 
#      ¶¶¶¶¶¶¶¶¶¶    ¶¶  ¶¶ ¶¶¶ ¶¶  ¶¶        ¶¶¶ 
#        ¶¶¶   ¶¶  ¶¶¶¶ ¶¶¶ ¶  ¶¶¶              ¶¶¶ 
#       ¶¶    ¶¶ ¶¶¶ ¶¶¶  ¶¶¶  ¶¶             ¶¶¶¶¶¶
#      ¶¶     ¶¶¶¶¶  ¶¶   ¶¶                  ¶¶ 
#   ¶¶¶¶¶¶¶                                    ¶ 
#     ¶ ¶ ¶¶¶                                   ¶¶ 
#         ¶¶                              ¶¶¶¶¶¶¶¶¶¶
#        ¶¶    ¶¶                ¶    ¶¶¶  ¶¶  ¶ 
#     ¶¶¶¶¶¶¶¶¶¶¶           ¶¶   ¶¶¶   ¶¶¶¶¶¶¶ 
#        ¶¶¶¶   ¶  ¶¶¶¶  ¶¶ ¶¶¶  ¶¶¶¶¶¶¶¶ 
#             ¶¶¶¶¶¶ ¶¶ ¶¶¶¶¶¶¶¶¶¶    ¶¶¶¶ 
#             ¶¶¶¶   ¶¶¶¶¶¶¶¶¶¶¶ ¶¶ 
#                      ¶¶¶¶¶¶¶¶¶ 
#                      ¶¶¶¶¶¶¶¶¶


from django.db import migrations


class Migration(migrations.Migration):

    #Change to form
    dependencies = [
        ('form', '0024_remove_universities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SemesterYear'
        ),
        migrations.DeleteModel(
            name='Grade'
        ),
        migrations.DeleteModel(
            name='Publication'
        ),
        migrations.DeleteModel(
            name='UniversityThrough'
        ),
        migrations.DeleteModel(
            name='RegularLanguageCertificate'
        ),
        migrations.DeleteModel(
            name='GMATCertificate'
        ),
        migrations.DeleteModel(
            name='GREGeneralCertificate'
        ),
        migrations.DeleteModel(
            name='GREBiologyCertificate'
        ),
        migrations.DeleteModel(
            name='GREPhysicsCertificate'
        ),
        migrations.DeleteModel(
            name='GREPsychologyCertificate'
        ),
        migrations.DeleteModel(
            name='DuolingoCertificate'
        ),
        migrations.DeleteModel(
            name='GRESubjectCertificate'
        ),
        migrations.DeleteModel(
            name='LanguageCertificate'
        ),
    ]