# Generated by Hossein Mohammadi on 2021-01-01


# ##    ##      ##      ####   ####   ##   ##    ░█████╗░██╗░░██╗██████╗░██╗░██████╗████████╗███╗░░░███╗░█████╗░░██████╗
# ##    ##     ####     ## ##  ## ##   ## ##     ██╔══██╗██║░░██║██╔══██╗██║██╔════╝╚══██╔══╝████╗░████║██╔══██╗██╔════╝
# ########    ## # #    ####   ####     ###      ██║░░╚═╝███████║██████╔╝██║╚█████╗░░░░██║░░░██╔████╔██║███████║╚█████╗░
# ##    ##   ##    ##   ##     ##        #       ██║░░██╗██╔══██║██╔══██╗██║░╚═══██╗░░░██║░░░██║╚██╔╝██║██╔══██║░╚═══██╗
# ##    ##  ##      ##  ##     ##        #       ╚█████╔╝██║░░██║██║░░██║██║██████╔╝░░░██║░░░██║░╚═╝░██║██║░░██║██████╔╝


from django.db import migrations


class Migration(migrations.Migration):
    # Change to form
    dependencies = [
        ('form', '0027_delete_redundant_objects_with_applydata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetailedinfo',
            name='universities',
        ),
    ]