# Generated by Django 3.1.1 on 2021-01-03 23:40

from django.db import migrations, models


def create_new_id(apps, schema_editor):
    print('for base')
    StudentDetailedInfoBase = apps.get_model('form', 'studentdetailedinfobase')
    id = 1
    for sdib in StudentDetailedInfoBase.objects.all():
        sdib.new_id = id
        sdib.save()
        id += 1
    # for sdib in StudentDetailedInfoBase.objects.all():
    #     print(sdib.new_id)


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0029_delete_deprecated_models_from_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetailedinfobase',
            name='new_id',
            field=models.IntegerField(default=1, serialize=False, null=True, verbose_name='NEW_ID', editable=False),
        ),
        migrations.RunPython(create_new_id, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studentdetailedinfobase',
            name='new_id',
            field=models.IntegerField(default=1, serialize=False, unique=True, verbose_name='NEW_ID', editable=False),
        )
    ]
