# Generated by Django 3.1.1 on 2021-01-04 00:28

from django.db import migrations, models


def create_new_id(apps, schema_editor):
    StudentDetailedInfo = apps.get_model('form', 'studentdetailedinfo')
    for sdi in StudentDetailedInfo.objects.all():
        sdi.local_new_id = sdi.new_id
        sdi.save()


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0030_studentdetailedinfobase_new_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='local_new_id',
            field=models.IntegerField(auto_created=True, default=1, serialize=False, null=True,
                                      verbose_name='NEW_ID', ),
        ),
        migrations.RunPython(create_new_id, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='local_new_id',
            field=models.IntegerField(auto_created=True, default=1, serialize=False, unique=True,
                                      verbose_name='NEW_ID', ),
        )
    ]
