# Generated by Django 3.1.1 on 2021-01-06 11:02

from django.db import migrations, models

# Before disable inheritance


def create_new_id(apps, schema_editor):
    print('for child')
    StudentDetailedInfo = apps.get_model('form', 'studentdetailedinfo')
    for sdi in StudentDetailedInfo.objects.all():
        sdi.local_new_id = sdi.new_id
        sdi.save()
    for sdi in StudentDetailedInfo.objects.all():
        print(sdi.local_new_id)


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0030_studentdetailedinfobase_new_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='local_new_id',
            field=models.IntegerField(serialize=False, null=True, verbose_name='LOCAL_NEW_ID', editable=False),
        ),
        migrations.RunPython(create_new_id, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='local_new_id',
            field=models.IntegerField(serialize=False, unique=True, verbose_name='LOCAL_NEW_ID', editable=False),
        )
    ]
