# Generated by Django 3.1.1 on 2021-01-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0031_studentdetailedinfo_local_new_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanttoapply',
            name='student_detailed_info',
            field=models.UUIDField(),
        ),
    ]
