# Generated by Django 3.1.1 on 2021-01-06 12:37

from django.db import migrations, models


# Here in first operation inheritance is removed

class Migration(migrations.Migration):

    dependencies = [
        ('form', '0033_auto_20210106_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetailedinfo',
            name='studentdetailedinfobase_ptr',
        ),
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='local_new_id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='LOCAL_NEW_ID'),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfobase',
            name='new_id',
            field=models.IntegerField(auto_created=True, default=1, serialize=False, unique=True, verbose_name='NEW_ID'),
        ),
    ]
