# Generated by Django 3.1.1 on 2021-01-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0034_auto_20210106_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfobase',
            name='id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='studentdetailedinfobase',
            name='new_id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='NEW_ID'),
        ),
    ]
