# Generated by Django 3.1.1 on 2021-01-04 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0033_auto_20210104_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False
            ),)]

