# Generated by Django 3.1.1 on 2021-01-06 13:24

from django.db import migrations, models
import django.db.models.deletion


def set_sdi(apps, schema_editor):
    print('for base')
    StudentDetailedInfoBase = apps.get_model('form', 'studentdetailedinfobase')
    StudentDetailedInfo = apps.get_model('form', 'studentdetailedinfo')
    WantToApply = apps.get_model('form', 'wanttoapply')
    for wta in WantToApply.objects.all():
        new_id = StudentDetailedInfoBase.objects.get(old_id=wta.student_detailed_info_old).id
        sdi = StudentDetailedInfo.objects.get(local_new_id=new_id)
        wta.student_detailed_info = sdi
        wta.save()
    # for sdib in StudentDetailedInfoBase.objects.all():
    #     print(sdib.new_id)


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0037_auto_20210106_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanttoapply',
            name='student_detailed_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='want_to_apply', to='form.studentdetailedinfo'),
        ),
        migrations.RunPython(code=set_sdi, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='wanttoapply',
            name='student_detailed_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='want_to_apply', to='form.studentdetailedinfo'),
        ),
    ]
