# Generated by Django 3.1.1 on 2021-01-06 13:35
import uuid

from django.contrib.contenttypes.models import ContentType
from django.db import connection
from django.db import migrations


def forwards_func(apps, schema_editor, model_name):

    db_name = connection.settings_dict['NAME']
    # print(db_name)
    if db_name.startswith('test'):
        return

    print(model_name)
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    # ContentType = apps.get_model("contenttypes", 'contenttype')
    sdi_content_type = ContentType.objects.get(app_label='form', model='studentdetailedinfo')
    sdib_content_type = ContentType.objects.get(app_label='form', model='studentdetailedinfobase')
    ApplyDataModel = apps.get_model("applydata", model_name)
    StudentDetailedInfoBase = apps.get_model('form', 'studentdetailedinfobase')
    StudentDetailedInfo = apps.get_model('form', 'studentdetailedinfo')
    for obj in ApplyDataModel.objects.filter(content_type__id=sdi_content_type.id):
        try:
            uuid_id = uuid.UUID(obj.object_id)
            new_id = StudentDetailedInfoBase.objects.get(old_id=uuid_id).id
            obj.object_id = new_id
            obj.save()
        except ValueError:
            pass
    for obj in ApplyDataModel.objects.filter(content_type__id=sdib_content_type.id):
        try:
            uuid_id = uuid.UUID(obj.object_id)
            new_id = StudentDetailedInfoBase.objects.get(old_id=uuid_id).id
            obj.object_id = new_id
            obj.save()
        except ValueError:
            pass


def reverse_func(apps, schema_editor, model_name):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    sdi_content_type = ContentType.objects.get(app_label='form', model='studentdetailedinfo')
    ApplyData = apps.get_model("applydata", model_name)
    StudentDetailedInfoBase = apps.get_model('form', 'studentdetailedinfobase')
    StudentDetailedInfo = apps.get_model('form', 'studentdetailedinfo')
    for obj in ApplyData.objects.filter(content_type__id=sdi_content_type.id):
        try:
            int(obj.object_id)
            old_id = StudentDetailedInfoBase.objects.get(id=obj.object_id).old_id
            obj.object_id = old_id
            obj.save()
        except ValueError:
            pass


def func_decorator(func, model_name):
    def wrapper(apps, schema_editor):
        return func(apps, schema_editor, model_name)
    return wrapper


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0038_wanttoapply_student_detailed_info3'),
    ]

    operations = [
        migrations.RunPython(
            code=func_decorator(forwards_func, 'publication'), reverse_code=func_decorator(reverse_func, 'publication')),
        migrations.RunPython(
            code=func_decorator(forwards_func, 'education'), reverse_code=func_decorator(reverse_func, 'education')),
        migrations.RunPython(
            code=func_decorator(forwards_func, 'languagecertificate'), reverse_code=func_decorator(reverse_func, 'languagecertificate')),
        migrations.RunPython(
            code=func_decorator(forwards_func, 'regularlanguagecertificate'), reverse_code=func_decorator(reverse_func, 'regularlanguagecertificate')),
        migrations.RunPython(
            code=func_decorator(forwards_func, 'gmatcertificate'), reverse_code=func_decorator(reverse_func, 'gmatcertificate')),
        migrations.RunPython(
            code=func_decorator(forwards_func, 'gregeneralcertificate'), reverse_code=func_decorator(reverse_func, 'gregeneralcertificate')),
        migrations.RunPython(
            code=func_decorator(forwards_func, 'gresubjectcertificate'), reverse_code=func_decorator(reverse_func, 'gresubjectcertificate')),
        migrations.RunPython(
            code=func_decorator(forwards_func, 'grebiologycertificate'), reverse_code=func_decorator(reverse_func, 'grebiologycertificate')),
        migrations.RunPython(
            code=func_decorator(forwards_func, 'grephysicscertificate'), reverse_code=func_decorator(reverse_func, 'grephysicscertificate')),
        migrations.RunPython(
            code=func_decorator(forwards_func, 'grepsychologycertificate'), reverse_code=func_decorator(reverse_func, 'grepsychologycertificate')),
        migrations.RunPython(
            code=func_decorator(forwards_func, 'duolingocertificate'), reverse_code=func_decorator(reverse_func, 'duolingocertificate')),
    ]
