# Generated by Django 3.1.1 on 2021-01-06 13:35
import uuid

from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def forwards_func(apps, schema_editor, model_name):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    sdi_content_type = ContentType.objects.get(app_label='form', model='studentdetailedinfo')
    ApplyData = apps.get_model("applydata", model_name)
    StudentDetailedInfoBase = apps.get_model('form', 'studentdetailedinfobase')
    StudentDetailedInfo = apps.get_model('form', 'studentdetailedinfo')
    for obj in ApplyData.objects.filter(content_type__id=sdi_content_type.id):
        new_id = StudentDetailedInfoBase.objects.get(old_id=uuid.UUID(obj.object_id)).id
        obj.object_id = str(new_id)
        obj.save()


def reverse_func(apps, schema_editor, model_name):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    sdi_content_type = ContentType.objects.get(app_label='form', model='studentdetailedinfo')
    ApplyData = apps.get_model("applydata", model_name)
    StudentDetailedInfoBase = apps.get_model('form', 'studentdetailedinfobase')
    StudentDetailedInfo = apps.get_model('form', 'studentdetailedinfo')
    for obj in ApplyData.objects.filter(content_type__id=sdi_content_type.id):
        old_id = StudentDetailedInfoBase.objects.get(id=int(obj.object_id)).old_id
        obj.object_id = str(old_id)
        obj.save()


def func_decorator(func, model_name):
    def wrapper(apps, schema_editor):
        return func(apps, schema_editor, model_name)
    return wrapper


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0038_wanttoapply_student_detailed_info'),
    ]

    operations = [
        migrations.RunPython(
            code=func_decorator(forwards_func, 'publication'), reverse_code=func_decorator(reverse_func, 'publication')),
        migrations.RunPython(
            code=func_decorator(forwards_func, 'education'), reverse_code=func_decorator(reverse_func, 'education')),
        migrations.RunPython(
            code=func_decorator(forwards_func, 'regularlanguagecertificate'), reverse_code=func_decorator(reverse_func, 'regularlanguagecertificate')),
        migrations.RunPython(
            code=func_decorator(forwards_func, 'gmatcertificate'), reverse_code=func_decorator(reverse_func, 'gmatcertificate')),
        migrations.RunPython(
            code=func_decorator(forwards_func, 'gregeneralcertificate'), reverse_code=func_decorator(reverse_func, 'gregeneralcertificate')),
        migrations.RunPython(
            code=func_decorator(forwards_func, 'gresubjectcertificate'), reverse_code=func_decorator(reverse_func, 'gresubjectcertificate')),
        migrations.RunPython(
            code=func_decorator(forwards_func, 'grebiologycertificate'), reverse_code=func_decorator(reverse_func, 'grebiologycertificate')),
        migrations.RunPython(
            code=func_decorator(forwards_func, 'grephysicscertificate'), reverse_code=func_decorator(reverse_func, 'grephysicscertificate')),
        migrations.RunPython(
            code=func_decorator(forwards_func, 'grepsychologycertificate'), reverse_code=func_decorator(reverse_func, 'grepsychologycertificate')),
        migrations.RunPython(
            code=func_decorator(forwards_func, 'duolingocertificate'), reverse_code=func_decorator(reverse_func, 'duolingocertificate')),
    ]
