# Generated by Django 3.1.1 on 2021-01-06 14:20

from django.db import migrations, models
import django.db.models.deletion


# inheritance comes back :-*

class Migration(migrations.Migration):

    dependencies = [
        ('form', '0039_auto_20210106_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='local_new_id',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.studentdetailedinfobase'),
        ),
    ]
