# Generated by Django 3.1.1 on 2021-01-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0040_auto_20210106_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetailedinfo',
            old_name='local_new_id',
            new_name='studentdetailedinfobase_ptr',
        ),
    ]
