# Generated by Django 3.1.1 on 2021-01-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0041_auto_20210106_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfobase',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
