# Generated by Django 3.1.1 on 2021-01-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0042_auto_20210107_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfobase',
            name='old_id',
            field=models.UUIDField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='wanttoapply',
            name='student_detailed_info_old',
            field=models.UUIDField(null=True, blank=True),
        ),
    ]
