# Generated by Django 3.1.1 on 2021-01-09 13:09

import os

from django.db import migrations
from django.conf import settings


def change_file_dir(source, destination):
    os.rename(source, destination)


def new_file_upper_dir_relative_path(obj):
    return "account/files/form/{}".format(obj.id)


def new_file_upper_dir_absolute_path(obj):
    return '/'.join(settings.BASE_DIR.split('/')[:-1] + [settings.MEDIA_ROOT, new_file_upper_dir_relative_path(obj)])


def old_file_upper_dir_absolute_path(obj):
    try:
        return '/'.join(obj.resume.path.split('/')[:-2])
    except ValueError:
        return None


def update_resume_file_field(apps, schema_editor):
    StudentDetailedInfoBase = apps.get_model('form', 'studentdetailedinfobase')

    for obj in StudentDetailedInfoBase.objects.all():
        old_upper_dir_path = old_file_upper_dir_absolute_path(obj)
        if not old_upper_dir_path:
            continue
        new_upper_dir_path = new_file_upper_dir_absolute_path(obj)
        try:
            change_file_dir(old_upper_dir_path, new_upper_dir_path)
            obj.resume = new_upper_dir_path
            obj.save()
        except ValueError:
            pass
        except FileNotFoundError:
            print('no file in old path:', old_upper_dir_path)


def reverse_update_resume_file_field(apps, schema_editor):
    StudentDetailedInfoBase = apps.get_model('form', 'studentdetailedinfobase')

    for obj in StudentDetailedInfoBase.objects.all():
        old_upper_dir_path = old_file_upper_dir_absolute_path(obj)
        if not old_upper_dir_path:
            continue
        new_upper_dir_path = new_file_upper_dir_absolute_path(obj)
        try:
            change_file_dir(new_upper_dir_path, old_upper_dir_path)
            obj.resume = old_upper_dir_path
            obj.save()
        except ValueError:
            pass
        except FileNotFoundError:
            print('no file in new path:', new_upper_dir_path)


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0043_auto_20210108_1321'),
    ]

    operations = [
        migrations.RunPython(code=update_resume_file_field, reverse_code=migrations.RunPython.noop)
    ]
