# Generated by Django 3.1.1 on 2021-01-23 06:23

from django.conf import settings
from django.db import migrations, models


def delete_no_user_student_detailed_infos(apps, schema_editor):
    StudentDetailedInfo = apps.get_model('form', 'studentdetailedinfo')
    StudentDetailedInfo.objects.filter(user=None).delete()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0044_auto_20210109_1639'),
    ]

    operations = [
        migrations.RunPython(delete_no_user_student_detailed_infos),

    ]
