# Generated by Django 3.1.1 on 2021-01-23 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0045_auto_20210123_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customAuth.customuser'),
        ),
    ]
