# Generated by Django 3.1.1 on 2021-01-23 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0046_auto_20210123_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='age',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
