# Generated by Django 3.1.1 on 2021-01-23 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0047_auto_20210123_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=128),
            preserve_default=False,
        ),
    ]
