# Generated by Django 3.1.1 on 2021-01-23 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0048_auto_20210123_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailedinfo',
            name='powerful_recommendation',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentdetailedinfobase',
            name='academic_break',
            field=models.PositiveIntegerField(default=0, help_text='In years', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentdetailedinfobase',
            name='related_work_experience',
            field=models.PositiveIntegerField(default=0, help_text='In months'),
            preserve_default=False,
        ),
    ]
