# Generated by Django 2.2.3 on 2020-09-25 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('title', models.CharField(choices=[('GRADE_POINT_AVERAGE', 'Grade Point Average'), ('PUBLICATIONS_COUNT', 'Publications Count'), ('PUBLICATIONS_TYPE', 'Publications Type'), ('PUBLICATIONS_SCORE', 'Publications Score'), ('PUBLICATIONS_IMPACT_FACTOR', 'Publications Impact Factor'), ('POWERFUL_RECOMMENDATION', 'Powerful Recommendation'), ('OLYMPIAD', 'Olympiad'), ('RELATED_WORK_EXPERIENCE', 'Related Work Experience'), ('TOEFL', 'Toefl'), ('IELTS', 'Ielts'), ('GMAT', 'GMAT'), ('GRE_GENERAL_WRITING', 'GRE General Writing'), ('GRE_GENERAL_QUANTITATIVE_AND_VERBAL', 'GRE General Quantitative And Verbal'), ('GRE_SUBJECT_TOTAL', 'GRE Subject Total'), ('DUOLINGO', 'Duolingo')], max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChartItemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('count', models.FloatField(default=0)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.Chart')),
            ],
            options={
                'unique_together': {('label', 'chart')},
            },
        ),
    ]
