# Generated by Django 3.1.1 on 2020-10-01 09:04

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import sNeeds.apps.estimation.analyze.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('title', enumfields.fields.EnumField(enum=sNeeds.apps.estimation.analyze.models.ChartTitle, max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChartItemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('count', models.FloatField(default=0)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.chart')),
            ],
            options={
                'unique_together': {('label', 'chart')},
            },
        ),
    ]
