# Generated by Django 2.2.3 on 2020-07-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0022_auto_20200627_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soldstorepackage',
            options={'ordering': ['-updated']},
        ),
    ]
