# Generated by Django 2.2.3 on 2020-08-08 09:08

from django.db import migrations, models
import sNeeds.apps.storePackages.models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0023_auto_20200723_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldstorepackage',
            name='show_on_marketplace_until',
            field=models.DateTimeField(default=sNeeds.apps.storePackages.models.default_show_on_marketplace_until),
        ),
    ]
