# Generated by Django 3.1.1 on 2020-10-13 16:59

from django.db import migrations
from django.db.migrations import RunSQL


class Migration(migrations.Migration):

    sql = 'CREATE EXTENSION IF NOT EXISTS pg_trgm;'

    reverse_sql = 'DROP EXTENSION IF EXISTS pg_trgm;'

    dependencies = [
        ('account', '0005_auto_20201013_2010'),
    ]

    operations = [
        migrations.RunSQL(sql=sql, reverse_sql=reverse_sql)
    ]
