# Generated by Django 3.1.1 on 2021-02-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_provider',
            field=models.CharField(default='Email', max_length=255),
        ),
    ]
