# Generated by Django 3.1.1 on 2020-10-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the user email is verified.', verbose_name='email verification status'),
        ),
    ]
