# Generated by Django 3.1.1 on 2021-02-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0002_customuser_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_provider',
            field=models.CharField(choices=[('Email', 'Email'), ('Google', 'Google'), ('Facebook', 'Facebook')], default='Email', max_length=255),
        ),
    ]
