# Generated by Django 3.1.1 on 2020-11-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0004_auto_20201028_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_last_action',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
