# Generated by Django 3.1.1 on 2020-11-21 23:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0005_customuser_date_last_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='receive_marketing_email',
            field=models.BooleanField(default=False, help_text='Designates whether the user wants to get marketing emails or news.', verbose_name='receive marketing email status'),
        ),
    ]
