# Generated by Django 3.1.1 on 2020-11-22 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0005_customuser_date_last_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_last_action',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last action'),
        ),
    ]
