# Generated by Django 3.1.1 on 2020-11-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0006_auto_20201122_0325'),
        ('customAuth', '0006_auto_20201122_1354'),
    ]

    operations = [
    ]
