# Generated by Django 3.1.1 on 2021-02-01 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globaldata', '0001_initial'),
        ('applydata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gap', models.PositiveSmallIntegerField(default=0, help_text='In months')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField()),
                ('scholarship', models.PositiveIntegerField()),
                ('enroll_year', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, max_length=4096, null=True)),
                ('apply_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', related_query_name='admission', to='applyprofile.applyprofile')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='globaldata.university')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applydata.grade')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='globaldata.major')),
            ],
        ),
    ]
