# Generated by Django 3.1.1 on 2020-12-27 13:09

import abroadin.apps.applyprofile.models
from django.db import migrations, models
import django.db.models.deletion



def _get_other_country_id():
    pass


def _get_other_university_id():
    pass

def _get_other_major_id():
    pass



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0009_auto_20201222_1050'),
        ('applydata', '0004_auto_20210107_1216')
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('academic_gap', models.PositiveSmallIntegerField(default=0, help_text='In months')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_year', models.PositiveSmallIntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('scholarships', models.PositiveIntegerField()),
                ('scholarships_unit', models.CharField(choices=[('$/M', '$/M'), ('$/Y', '$/Y'), ('€/M', '€/M'), ('€/Y', '€/Y')], help_text='Scholarship unit. For example $/Y or €/M', max_length=8)),
                ('description', models.TextField(blank=True, max_length=4096, null=True)),
                ('apply_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applyprofile.applyprofile')),
                ('destination_university', models.ForeignKey(on_delete=models.SET(_get_other_university_id), related_name='admission_goal_universities', related_query_name='admission_goal_university', to='account.university')),
                ('major', models.ForeignKey(on_delete=models.SET(_get_other_major_id), to='account.major')),
                ('origin_university', models.ForeignKey(on_delete=models.SET(_get_other_university_id), related_name='admission_origin_universities', related_query_name='admission_origin_university', to='account.university')),
            ],
        ),
    ]
