# Generated by Django 3.1.1 on 2021-01-02 22:10

import abroadin.apps.applyprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20201222_1050'),
        ('applyprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='destination_university',
            field=models.ForeignKey(on_delete=models.SET(abroadin.apps.applyprofile.models._get_other_university_id), related_name='admission_destination_universities', related_query_name='admission_destination_university', to='account.university'),
        ),
    ]
