# Generated by Django 3.1.1 on 2021-04-18 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globaldata', '0001_initial'),
        ('applydata', '0002_auto_20210418_1743'),
        ('applyprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='globaldata.university'),
        ),
        migrations.AddField(
            model_name='admission',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applydata.grade'),
        ),
        migrations.AddField(
            model_name='admission',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='globaldata.major'),
        ),
    ]
