# Generated by Django 3.1.1 on 2021-01-15 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20201222_1050'),
        ('applyprofile', '0002_auto_20210103_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='destination_university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_destination_universities', related_query_name='admission_destination_university', to='account.university'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.major'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='origin_university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_origin_universities', related_query_name='admission_origin_university', to='account.university'),
        ),
    ]
