# Generated by Django 3.1.1 on 2021-01-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyprofile', '0003_auto_20210115_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='accepted',
            field=models.BooleanField(),
        ),
    ]
