# Generated by Django 3.1.1 on 2021-01-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applyprofile', '0004_auto_20210115_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='scholarships',
            new_name='scholarship',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='scholarships_unit',
            new_name='scholarship_unit',
        ),
    ]
