# Generated by Django 3.1.1 on 2021-01-15 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20201222_1050'),
        ('applyprofile', '0005_auto_20210115_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='destination_university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions_destination', to='account.university'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='origin_university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions_home', to='account.university'),
        ),
    ]
