# Generated by Django 3.1.1 on 2021-01-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applyprofile', '0006_auto_20210115_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='destination_university',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='origin_university',
            new_name='home',
        ),
    ]
