# Generated by Django 3.1.1 on 2021-01-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyprofile', '0007_auto_20210115_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyprofile',
            old_name='academic_gap',
            new_name='gap',
        ),
        migrations.AlterField(
            model_name='admission',
            name='scholarship_unit',
            field=models.CharField(choices=[('$/M', '$/M'), ('$/Y', '$/Y'), ('€/M', '€/M'), ('€/Y', '€/Y')], max_length=8),
        ),
    ]
