# Generated by Django 3.1.1 on 2021-01-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applydata', '0004_auto_20210107_1216'),
        ('applyprofile', '0008_auto_20210115_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='grade',
            field=models.ForeignKey(default=3000, on_delete=django.db.models.deletion.PROTECT, to='applydata.grade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='apply_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', related_query_name='admission', to='applyprofile.applyprofile'),
        ),
    ]
