# Generated by Django 3.1.1 on 2021-01-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applyprofile', '0009_auto_20210115_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='scholarship_unit',
        ),
    ]
