# Generated by Django 3.1.1 on 2021-01-15 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210115_2005'),
        ('applyprofile', '0010_remove_admission_scholarship_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='home',
        ),
        migrations.AlterField(
            model_name='admission',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.university'),
        ),
    ]
