# Generated by Django 3.1.1 on 2021-04-18 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('storeBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sold_products',
            field=models.ManyToManyField(blank=True, to='storeBase.SoldProduct'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
