# Generated by Django 3.1.1 on 2020-10-01 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedStudentDetailedInfo',
            fields=[
                ('studentdetailedinfobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.studentdetailedinfobase')),
            ],
            bases=('account.studentdetailedinfobase',),
        ),
        migrations.CreateModel(
            name='AppliedTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund', models.IntegerField(blank=True, help_text='In Dollars', null=True)),
                ('accepted', models.BooleanField()),
                ('comment', models.CharField(blank=True, max_length=1024, null=True)),
                ('applied_student_detailed_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_to', to='similarApply.appliedstudentdetailedinfo')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.country')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.grademodel')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.fieldofstudy')),
                ('semester_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.studentformapplysemesteryear')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.university')),
            ],
        ),
    ]
