# Generated by Django 3.1.1 on 2020-10-04 10:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import abroadin.apps.store.storePackages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storeBase', '0001_initial'),
        ('consultants', '0002_auto_20201004_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldStorePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('image', models.ImageField(blank=True, null=True, upload_to=abroadin.apps.store.storePackages.models.get_sold_store_package_image_upload_path)),
                ('paid_price', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultants.consultantprofile')),
                ('sold_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='StorePackage',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storeBase.product')),
                ('title', models.CharField(max_length=1024)),
                ('image', models.ImageField(blank=True, null=True, upload_to=abroadin.apps.store.storePackages.models.get_store_package_image_upload_path)),
                ('slug', models.SlugField(unique=True)),
                ('total_price', models.PositiveIntegerField(blank=True)),
            ],
            bases=('storeBase.product',),
        ),
        migrations.CreateModel(
            name='StorePackagePhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='StorePackagePhaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'شروع نشده'), ('in_progress', 'در حال انجام'), ('done', 'انجام شد'), ('finished', 'دریافت نتیجه'), ('pending_user_data', 'دریافت اطلاعات کاربر')], default='not_started', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='StorePackagePhaseThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('store_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storePackages.storepackage')),
                ('store_package_phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storePackages.storepackagephase')),
            ],
            options={
                'ordering': ['phase_number'],
                'unique_together': {('store_package', 'phase_number'), ('store_package', 'store_package_phase')},
            },
        ),
        migrations.AddField(
            model_name='storepackagephase',
            name='phase_details',
            field=models.ManyToManyField(blank=True, to='storePackages.StorePackagePhaseDetail'),
        ),
        migrations.AddField(
            model_name='storepackage',
            name='store_package_phases',
            field=models.ManyToManyField(related_name='store_packages', through='storePackages.StorePackagePhaseThrough', to='storePackages.StorePackagePhase'),
        ),
        migrations.CreateModel(
            name='SoldStoreUnpaidPackagePhase',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storeBase.product')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('phase_number', models.IntegerField()),
                ('status', models.CharField(choices=[('not_started', 'شروع نشده'), ('pay_to_start', 'نیازمند پرداخت برای شروع'), ('in_progress', 'در حال انجام'), ('done', 'انجام شده')], default='not_started', max_length=128)),
                ('sold_store_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storePackages.soldstorepackage')),
            ],
            options={
                'ordering': ['phase_number'],
                'abstract': False,
            },
            bases=('storeBase.product', models.Model),
        ),
        migrations.CreateModel(
            name='SoldStorePaidPackagePhase',
            fields=[
                ('soldproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storeBase.soldproduct')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('phase_number', models.IntegerField()),
                ('status', models.CharField(choices=[('not_started', 'شروع نشده'), ('pay_to_start', 'نیازمند پرداخت برای شروع'), ('in_progress', 'در حال انجام'), ('done', 'انجام شده')], default='not_started', max_length=128)),
                ('consultant_done', models.BooleanField(default=False)),
                ('sold_store_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storePackages.soldstorepackage')),
            ],
            options={
                'ordering': ['phase_number'],
                'abstract': False,
            },
            bases=('storeBase.soldproduct', models.Model),
        ),
        migrations.CreateModel(
            name='SoldStorePackagePhaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('not_started', 'شروع نشده'), ('in_progress', 'در حال انجام'), ('done', 'انجام شد'), ('finished', 'دریافت نتیجه'), ('pending_user_data', 'دریافت اطلاعات کاربر')], max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=abroadin.apps.store.storePackages.models.get_sold_store_package_phase_detail_file_upload_path)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'storePackages'), ('model', 'soldstorepaidpackagephase')), models.Q(('app_label', 'storePackages'), ('model', 'soldstoreunpaidpackagephase')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantSoldStorePackageAcceptRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultants.consultantprofile')),
                ('sold_store_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storePackages.soldstorepackage')),
            ],
            options={
                'unique_together': {('sold_store_package', 'consultant')},
            },
        ),
    ]
