# Generated by Django 3.1.1 on 2020-10-04 13:43

from django.db import migrations, models
import abroadin.apps.store.storePackages.models


class Migration(migrations.Migration):

    dependencies = [
        ('storePackages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soldstorepackage',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='soldstorepackage',
            name='show_on_marketplace_until',
            field=models.DateTimeField(default=abroadin.apps.store.storePackages.models.default_show_on_marketplace_until),
        ),
    ]
