# Generated by Django 3.1.1 on 2021-02-01 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applyprofile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storeBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldApplyProfileGroup',
            fields=[
                ('soldproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storeBase.soldproduct')),
                ('apply_profiles', models.ManyToManyField(to='applyprofile.ApplyProfile')),
            ],
            bases=('storeBase.soldproduct',),
        ),
        migrations.CreateModel(
            name='ApplyProfileGroup',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storeBase.product')),
                ('apply_profiles', models.ManyToManyField(to='applyprofile.ApplyProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('storeBase.product',),
        ),
    ]
