# Generated by Django 3.1.1 on 2021-01-21 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applyprofilestore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldapplyprofilegroup',
            name='user',
        ),
    ]
