# Generated by Django 3.1.1 on 2020-10-03 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetailedinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='languagecertificate',
            unique_together={('certificate_type', 'student_detailed_info')},
        ),
        migrations.AddField(
            model_name='fieldofstudy',
            name='major_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.fieldofstudytype'),
        ),
    ]
