# Generated by Django 3.1.1 on 2021-01-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0031_auto_20210104_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanttoapply',
            name='student_detailed_info',
            field=models.UUIDField(),
        ),
    ]
