# Generated by Django 3.1.1 on 2021-01-04 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0032_auto_20210104_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wanttoapply',
            old_name='student_detailed_info',
            new_name='student_detailed_info_old',
        )
        ]
