# Generated by Django 3.1.1 on 2021-01-04 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0032_auto_20210104_0413'),
    ]
    sql1 = "ALTER TABLE from_studentdetailedinfo DROP CONSTRAINT "
    sql2 = "ALTER INDEX uniq_1483a5e93414710b RENAME TO users_pkey"

    operations = [
        migrations.RunSQL(sql='', reverse_sql="ALTER TABLE form_studentdetailedinfo ADD CONSTRAINT form_studentdetailed_studentdetailedinfob_adc5bac8_fk_form_stud FOREIGN KEY (studentdetailedinfobase_ptr_id) REFERENCES form_studentdetailedinfobase(id) DEFERRABLE INITIALLY DEFERRED;")
    ]
