# Generated by Django 3.1.1 on 2020-10-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similarApply', '0001_initial'),
    ]

    operations = [
    ]
