# Generated by Django 3.1.1 on 2020-10-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similarApply', '0003_auto_20201013_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedstudentdetailedinfo',
            name='student_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
