# Generated by Django 3.1.1 on 2020-10-26 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('similarApply', '0004_appliedstudentdetailedinfo_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedto',
            name='country',
        ),
    ]
