# Generated by Django 3.1.1 on 2021-01-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('similarApply', '0005_remove_appliedto_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppliedTo'
        ),
        migrations.DeleteModel(
            name='AppliedStudentDetailedInfo',
        ),

    ]
