# Generated by Django 3.1.1 on 2021-04-18 13:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicFormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('search_name', models.CharField(max_length=256, unique=True)),
                ('picture', models.FileField(blank=True, null=True, upload_to='globaldata/images/country-pictures', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
                ('slug', models.SlugField(help_text='Lowercase pls', unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('search_name', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='globaldata/images/university-pictures')),
                ('rank', models.PositiveIntegerField()),
                ('is_college', models.BooleanField(default=False)),
                ('submission_through', models.CharField(blank=True, max_length=128, null=True)),
                ('submission_path_note', models.CharField(blank=True, max_length=256, null=True)),
                ('currency', models.CharField(blank=True, max_length=4, null=True)),
                ('institution_type', models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], max_length=16, null=True)),
                ('accommodation_types', models.CharField(blank=True, choices=[('off-campus and on-campus', 'Off Campus On Campus')], max_length=32, null=True)),
                ('accommodation_information', models.TextField(blank=True, null=True)),
                ('coop_participating', models.BooleanField(blank=True, null=True)),
                ('coop_length', models.IntegerField(blank=True, null=True)),
                ('esl_is_academic_dependant', models.BooleanField(blank=True, null=True)),
                ('establishment_type', models.CharField(blank=True, choices=[('College', 'College'), ('English Institute', 'English Institute'), ('University', 'University'), ('High School', 'High School')], max_length=32, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('living_cost', models.IntegerField(blank=True, null=True)),
                ('avg_tuition', models.IntegerField(blank=True, null=True)),
                ('total_students', models.IntegerField(blank=True, null=True)),
                ('international_students', models.IntegerField(blank=True, null=True)),
                ('conditional_acceptance', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globaldata.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('video', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('search_name', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globaldata.major')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('province', models.CharField(blank=True, max_length=32, null=True)),
                ('postal', models.CharField(blank=True, max_length=16, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
