# Generated by Django 3.1.1 on 2021-03-06 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globaldata', '0002_auto_20210306_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='globaldata/images/country-pictures', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
