# Generated by Django 3.1.1 on 2021-04-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globaldata', '0005_auto_20210410_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='accommodation_types',
            field=models.CharField(blank=True, choices=[('off-campus and on-campus', 'Off Campus On Campus')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='establishment_type',
            field=models.CharField(blank=True, choices=[('College', 'College'), ('English Institute', 'English Institute'), ('University', 'University'), ('High School', 'High School')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], max_length=16, null=True),
        ),
    ]
