# Generated by Django 2.2.3 on 2020-05-16 13:33

from django.db import migrations
import enumfields.fields
from enum import Enum

import sNeeds.apps.notifications.models


class NotificationType(Enum):
    sold_time_slot_reminder = 1


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='user_type',
            field=enumfields.fields.EnumIntegerField(default=None, enum=NotificationType),
            preserve_default=False,
        ),
    ]
