[

    # "Bachelor", students with "No",  publication and others

    {
        "id": 0,
        'Grade': 'Bachelor',
        'University Rank': 50,
        'GPA': 18,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {
            'Admission': {'1to20': 'High',
                          '21to100': 'High',
                          '101to400': 'High',
                          '401to1000': 'High',
                          '1000above': 'High'},
            'Fund': {'1to20': 'Medium',
                     '21to100': 'High',
                     '101to400': 'High',
                     '401to1000': 'High',
                     '1000above': 'High'}},

    },

    {
        "id": 5,
        'Grade': 'Bachelor',
        'University Rank': 50,
        'GPA': 16.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Medium',
                             '21to100': 'Medium',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 10,
        'Grade': 'Bachelor',
        'University Rank': 50,
        'GPA': 14.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Low',
                                  '401to1000': 'Medium',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Low',
                             '401to1000': 'Low',
                             '1000above': 'High'}},

    },

    {
        "id": 15,
        'Grade': 'Bachelor',
        'University Rank': 200,
        'GPA': 19.75,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'High',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'High',
                             '21to100': 'High',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 20,
        'Grade': 'Bachelor',
        'University Rank': 200,
        'GPA': 17.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Medium',
                             '21to100': 'High',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 25,
        'Grade': 'Bachelor',
        'University Rank': 200,
        'GPA': 15.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Medium',
                                  '101to400': 'Medium',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Medium',
                             '401to1000': 'Medium',
                             '1000above': 'High'}},

    },

    {
        "id": 30,
        'Grade': 'Bachelor',
        'University Rank': 400,
        'GPA': 19,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'High',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Medium',
                             '21to100': 'High',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 35,
        'Grade': 'Bachelor',
        'University Rank': 400,
        'GPA': 17.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Medium',
                             '21to100': 'Medium',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 40,
        'Grade': 'Bachelor',
        'University Rank': 400,
        'GPA': 15.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Medium',
                                  '101to400': 'Medium',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Medium',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 45,
        'Grade': 'Bachelor',
        'University Rank': 500,
        'GPA': 14.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Low',
                                  '401to1000': 'Medium',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Low',
                             '401to1000': 'Low',
                             '1000above': 'High'}},

    },

    {
        "id": 50,
        'Grade': 'Bachelor',
        'University Rank': 650,
        'GPA': 17.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'Medium',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Medium',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 55,
        'Grade': 'Bachelor',
        'University Rank': 650,
        'GPA': 16.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Medium',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Medium',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 60,
        'Grade': 'Bachelor',
        'University Rank': 650,
        'GPA': 12.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Low',
                                  '401to1000': 'Low',
                                  '1000above': 'Medium'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Low',
                             '401to1000': 'Low',
                             '1000above': 'High'}},

    },

    {
        "id": 65,
        'Grade': 'Bachelor',
        'University Rank': 900,
        'GPA': 18.75,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Medium',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 70,
        'Grade': 'Bachelor',
        'University Rank': 900,
        'GPA': 14.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Low',
                                  '401to1000': 'Low',
                                  '1000above': 'Medium'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Low',
                             '401to1000': 'Low',
                             '1000above': 'High'}},

    },

    {
        "id": 75,
        'Grade': 'Bachelor',
        'University Rank': 2000,
        'GPA': 19.75,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'Medium',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Medium',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 80,
        'Grade': 'Bachelor',
        'University Rank': 2000,
        'GPA': 18.75,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Medium',
                             '21to100': 'Medium',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 85,
        'Grade': 'Bachelor',
        'University Rank': 2000,
        'GPA': 17.75,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Medium',
                             '21to100': 'Medium',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 90,
        'Grade': 'Bachelor',
        'University Rank': 2000,
        'GPA': 16.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Medium',
                                  '101to400': 'Medium',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Medium',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 95,
        'Grade': 'Bachelor',
        'University Rank': 2000,
        'GPA': 15.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Medium',
                                  '401to1000': 'Medium',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Low',
                             '401to1000': 'Medium',
                             '1000above': 'High'}},

    },

    {
        "id": 100,
        'Grade': 'Bachelor',
        'University Rank': 2000,
        'GPA': 14.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Low',
                                  '401to1000': 'Low',
                                  '1000above': 'Medium'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Low',
                             '401to1000': 'Low',
                             '1000above': 'High'}},

    },

    {
        "id": 105,
        'Grade': 'Bachelor',
        'University Rank': 2000,
        'GPA': 12.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {
            'Admission': {'1to20': 'Low',
                          '21to100': 'Low',
                          '101to400': 'Low',
                          '401to1000': 'Low',
                          '1000above': 'Low'},
            'Fund': {'1to20': 'Low',
                     '21to100': 'Low',
                     '101to400': 'Low',
                     '401to1000': 'Low',
                     '1000above': 'Low'}},

    },

    # "Master",  students with "No",  publication and others

    {
        "id": 110,
        'Grade': 'Master',
        'University Rank': 50,
        'GPA': 18,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'Medium',
                                  '101to400': 'Medium',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Medium',
                             '101to400': 'Medium',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 115,
        'Grade': 'Master',
        'University Rank': 50,
        'GPA': 16.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Medium',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Medium',
                             '401to1000': 'Medium',
                             '1000above': 'High'}},

    },

    {
        "id": 120,
        'Grade': 'Master',
        'University Rank': 50,
        'GPA': 14.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Low',
                                  '401to1000': 'Medium',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Low',
                             '401to1000': 'Low',
                             '1000above': 'High'}},

    },

    {
        "id": 125,
        'Grade': 'Master',
        'University Rank': 200,
        'GPA': 19.75,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Medium',
                             '21to100': 'Medium',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 130,
        'Grade': 'Master',
        'University Rank': 200,
        'GPA': 17.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'Medium',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Medium',
                             '101to400': 'Medium',
                             '401to1000': 'Medium',
                             '1000above': 'High'}},

    },

    {
        "id": 135,
        'Grade': 'Master',
        'University Rank': 200,
        'GPA': 15.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Medium',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Low',
                             '401to1000': 'Medium',
                             '1000above': 'High'}},

    },

    {
        "id": 140,
        'Grade': 'Master',
        'University Rank': 400,
        'GPA': 19,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Medium',
                             '21to100': 'Medium',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 145,
        'Grade': 'Master',
        'University Rank': 400,
        'GPA': 17.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'Medium',
                                  '101to400': 'Medium',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Medium',
                             '101to400': 'Medium',
                             '401to1000': 'Medium',
                             '1000above': 'High'}},

    },

    {
        "id": 150,
        'Grade': 'Master',
        'University Rank': 400,
        'GPA': 15.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Medium',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Low',
                             '401to1000': 'Medium',
                             '1000above': 'High'}},

    },

    {
        "id": 155,
        'Grade': 'Master',
        'University Rank': 500,
        'GPA': 14.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Low',
                                  '401to1000': 'Medium',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Low',
                             '401to1000': 'Low',
                             '1000above': 'High'}},

    },

    {
        "id": 160,
        'Grade': 'Master',
        'University Rank': 650,
        'GPA': 17.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Medium',
                                  '101to400': 'Medium',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Medium',
                             '401to1000': 'Medium',
                             '1000above': 'High'}},

    },

    {
        "id": 165,
        'Grade': 'Master',
        'University Rank': 650,
        'GPA': 16.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Medium',
                                  '401to1000': 'Medium',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Low',
                             '401to1000': 'Medium',
                             '1000above': 'High'}},

    },

    {
        "id": 170,
        'Grade': 'Master',
        'University Rank': 650,
        'GPA': 12.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {
            'Admission': {'1to20': 'Low',
                          '21to100': 'Low',
                          '101to400': 'Low',
                          '401to1000': 'Low',
                          '1000above': 'Low'},
            'Fund': {'1to20': 'Low',
                     '21to100': 'Low',
                     '101to400': 'Low',
                     '401to1000': 'Low',
                     '1000above': 'High'}},

    },

    {
        "id": 175,
        'Grade': 'Master',
        'University Rank': 900,
        'GPA': 18.75,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'High',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Medium',
                             '21to100': 'Medium',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 180,
        'Grade': 'Master',
        'University Rank': 900,
        'GPA': 14.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Low',
                                  '401to1000': 'Low',
                                  '1000above': 'Medium'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Low',
                             '401to1000': 'Low',
                             '1000above': 'High'}},

    },

    {
        "id": 185,
        'Grade': 'Master',
        'University Rank': 2000,
        'GPA': 19.75,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Medium',
                             '21to100': 'Medium',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 190,
        'Grade': 'Master',
        'University Rank': 2000,
        'GPA': 18.75,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Medium',
                             '21to100': 'Medium',
                             '101to400': 'Medium',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 195,
        'Grade': 'Master',
        'University Rank': 2000,
        'GPA': 17.75,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Medium',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Medium',
                             '101to400': 'Medium',
                             '401to1000': 'Medium',
                             '1000above': 'High'}},

    },

    {
        "id": 200,
        'Grade': 'Master',
        'University Rank': 2000,
        'GPA': 16.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Medium',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Low',
                             '401to1000': 'Medium',
                             '1000above': 'High'}},

    },

    {
        "id": 205,
        'Grade': 'Master',
        'University Rank': 2000,
        'GPA': 15.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Low',
                                  '401to1000': 'Medium',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Low',
                             '401to1000': 'Low',
                             '1000above': 'High'}},

    },

    {
        "id": 210,
        'Grade': 'Master',
        'University Rank': 2000,
        'GPA': 14.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Low',
                                  '401to1000': 'Low',
                                  '1000above': 'Medium'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Low',
                             '401to1000': 'Low',
                             '1000above': 'High'}},

    },

    {
        "id": 215,
        'Grade': 'Master',
        'University Rank': 2000,
        'GPA': 12.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'No',
        'Others': 'No',

        'Chances': {
            'Admission': {'1to20': 'Low',
                          '21to100': 'Low',
                          '101to400': 'Low',
                          '401to1000': 'Low',
                          '1000above': 'Low'},
            'Fund': {'1to20': 'Low',
                     '21to100': 'Low',
                     '101to400': 'Low',
                     '401to1000': 'Low',
                     '1000above': 'Low'}},

    },

    # "Bachelor", students with publication

    {
        "id": 220,
        'Grade': 'Bachelor',
        'University Rank': 50,
        'GPA': 14.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'Very Good',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Medium',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 225,
        'Grade': 'Bachelor',
        'University Rank': 50,
        'GPA': 16,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'Medium',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Medium',
                             '101to400': 'Medium',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 230,
        'Grade': 'Bachelor',
        'University Rank': 400,
        'GPA': 17.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'Excellent',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Medium',
                             '21to100': 'High',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 235,
        'Grade': 'Bachelor',
        'University Rank': 400,
        'GPA': 16.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'Medium',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Medium',
                             '21to100': 'Medium',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 240,
        'Grade': 'Bachelor',
        'University Rank': 2000,
        'GPA': 16.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'Good',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Medium',
                             '21to100': 'High',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    # "Master",  students with publication

    {
        "id": 245,
        'Grade': 'Master',
        'University Rank': 50,
        'GPA': 14.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'Very Good',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Low',
                                  '401to1000': 'Medium',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Low',
                             '401to1000': 'Medium',
                             '1000above': 'High'}},

    },

    {
        "id": 250,
        'Grade': 'Master',
        'University Rank': 50,
        'GPA': 16,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'Medium',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Medium',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'High',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 255,
        'Grade': 'Master',
        'University Rank': 400,
        'GPA': 17.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'Excellent',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Medium',
                             '21to100': 'High',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 260,
        'Grade': 'Master',
        'University Rank': 400,
        'GPA': 16.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'Medium',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Medium',
                                  '101to400': 'Medium',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Medium',
                             '101to400': 'Medium',
                             '401to1000': 'Medium',
                             '1000above': 'High'}},

    },

    {
        "id": 265,
        'Grade': 'Master',
        'University Rank': 2000,
        'GPA': 16.5,
        'Language Cert Score': 7,
        'Language Cert Type': 'IELTS',
        'Publication': 'Good',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Medium',
                                  '101to400': 'Medium',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Medium',
                             '101to400': 'Medium',
                             '401to1000': 'Medium',
                             '1000above': 'High'}},

    },

    # "Bachelor", students with different language ranges ("No",  "Master",  needed)

    {
        "id": 270,
        'Grade': 'Bachelor',
        'University Rank': 50,
        'GPA': 14.5,
        'Language Cert Score': 8,
        'Language Cert Type': 'IELTS',
        'Publication': 'Very Good',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Low',
                                  '401to1000': 'Medium',
                                  '1000above': 'Medium'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Low',
                             '401to1000': 'Low',
                             '1000above': 'High'}},

    },

    {
        "id": 275,
        'Grade': 'Bachelor',
        'University Rank': 50,
        'GPA': 16,
        'Language Cert Score': 6,
        'Language Cert Type': 'IELTS',
        'Publication': 'Medium',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Low',
                                  '401to1000': 'Low',
                                  '1000above': 'Medium'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Low',
                             '401to1000': 'Low',
                             '1000above': 'High'}},

    },

    {
        "id": 280,
        'Grade': 'Bachelor',
        'University Rank': 400,
        'GPA': 17.5,
        'Language Cert Score': 7.5,
        'Language Cert Type': 'IELTS',
        'Publication': 'Excellent',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Medium',
                             '21to100': 'High',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 285,
        'Grade': 'Bachelor',
        'University Rank': 400,
        'GPA': 16.5,
        'Language Cert Score': 6.5,
        'Language Cert Type': 'IELTS',
        'Publication': 'Medium',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Medium',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Medium',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 290,
        'Grade': 'Bachelor',
        'University Rank': 2000,
        'GPA': 16.5,
        'Language Cert Score': 8,
        'Language Cert Type': 'IELTS',
        'Publication': 'Good',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Medium',
                             '101to400': 'Medium',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    # "Bachelor", and "Master",  students with publication and language

    {
        "id": 295,
        'Grade': 'Bachelor',
        'University Rank': 50,
        'GPA': 14.5,
        'Language Cert Score': 6,
        'Language Cert Type': 'IELTS',
        'Publication': 'Very Good',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Low',
                                  '101to400': 'Medium',
                                  '401to1000': 'Medium',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Low',
                             '101to400': 'Medium',
                             '401to1000': 'Medium',
                             '1000above': 'High'}},

    },

    {
        "id": 300,
        'Grade': 'Master',
        'University Rank': 50,
        'GPA': 16,
        'Language Cert Score': 8,
        'Language Cert Type': 'IELTS',
        'Publication': 'Medium',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Medium',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 305,
        'Grade': 'Bachelor',
        'University Rank': 400,
        'GPA': 17.5,
        'Language Cert Score': 6.5,
        'Language Cert Type': 'IELTS',
        'Publication': 'Excellent',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Medium',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Medium',
                             '21to100': 'High',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 310,
        'Grade': 'Master',
        'University Rank': 400,
        'GPA': 16.5,
        'Language Cert Score': 8,
        'Language Cert Type': 'IELTS',
        'Publication': 'Medium',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'High',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Medium',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    },

    {
        "id": 315,
        'Grade': 'Bachelor',
        'University Rank': 2000,
        'GPA': 16.5,
        'Language Cert Score': 7.5,
        'Language Cert Type': 'IELTS',
        'Publication': 'Good',
        'Others': 'No',

        'Chances': {'Admission': {'1to20': 'Low',
                                  '21to100': 'Medium',
                                  '101to400': 'High',
                                  '401to1000': 'High',
                                  '1000above': 'High'},
                    'Fund': {'1to20': 'Low',
                             '21to100': 'Medium',
                             '101to400': 'High',
                             '401to1000': 'High',
                             '1000above': 'High'}},

    }

]
